### ISSUE TITLE
Accessing management API from gateway proxy

### ISSUE THREAD

**Issue by girishmanwani** [gravitee-io/issues#1451] opened 2018-08-28 05:16 UTC
I have created a sampleapi for the endpoint http://SERVER:8005/management/applications/
The url for the gateway endpoint is http://SERVER:8000/queryapi
Calling http://SERVER:8000/queryapi via GET  by passing the API-KEY works fine.

However my requirement is to make a call to create a new Application
If I make a POST call and pass the following in body I get a error "401 Unauthorized"

{
	"api-key": "ffca4a2e-5dcf-4238-9eda-a70e4bf6c576",
	"name": "greetingDynaApp",
	"description": "Dynamic Greeting app",
	"type": "web"
}

Pl. advise.

**Comment by brasseld** [comment] 2018-08-28 06:35
Duplicate of https://github.com/gravitee-io/issues/issues/1448

You need an authorization header to create an application...

**Closed by brasseld** 2018-08-28 06:35 UTC
