### ISSUE TITLE
[Groovy] Content-Length is not update when using groovy OnRequestContent

### ISSUE THREAD

**Issue by Matsa59** [gravitee-io/issues#659] opened 2017-06-26 12:20 UTC
### Expected Behavior

Use OnRequestContent should send data define in the scope.

### Current Behavior

Data are been send, but the Content-Length header is not update. Server side does not consider the new content length. The new content will be cut or the server will return a timeout because content size is shorter than expected.

### Possible Solution

Update the Content-Length in the groovy or update the OnRequestContent behaviour to update automatically the content length using the return content.

### Steps to Reproduce (for bugs)

1. Add policy Groovy with ``` return "Hello world"; ``` in OnRequestContent
2. Request using POST method and a raw equal to `"Hello"`
3. Activate the HTTP dump and see the request content

**Comment by brasseld** [comment] 2017-06-26 12:23
Duplicate of https://github.com/gravitee-io/issues/issues/491

**Closed by brasseld** 2017-06-26 12:23 UTC
