### ISSUE TITLE
[portal] Useless "filter" field for empty category

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3479] opened 2020-04-08 05:52 UTC
See bottom right `Filtrer les résultats` 

<img width="1543" alt="Capture d’écran 2020-04-08 à 07 50 45" src="https://user-images.githubusercontent.com/133094/78749093-d5961380-796d-11ea-8698-5b3eb2543cc7.png">

**Comment by aelamrani** [comment] 2020-04-08 06:03
Duplicate of https://github.com/gravitee-io/issues/issues/3479

**Closed by aelamrani** 2020-04-08 06:03 UTC
Labels: project: APIM, type: uat
