### ISSUE TITLE
APIM : Adding new image in API Screen causing a input == null error

### ISSUE THREAD

**Issue by gravitee-eleshmistry** [gravitee-io/issues#6535] opened 2021-11-09 16:32 UTC
When adding an image on the API configuration screen an "input == null" error appears 

<img width="1130" alt="Screenshot 2021-11-09 at 16 21 26" src="https://user-images.githubusercontent.com/85284205/140963928-444f0f90-ecbb-4dee-bc3e-f8ee11959de5.png">

and it does not allow you to save the image.

### Expected Behavior
Should allow you to save and developer portal shows the image

### Current Behavior
"input == null" error appears 

### Steps to Reproduce (for bugs)
Version APIM 3.10.3
Go to API Creation Screen 
Add an image

### Context
Unable to configure the API

### Your Environment
* Version used: 3.10.3
* Browser Name and version: Chrome and Version 95.0.4638.69 (Official Build) (arm64)
* Operating System and version: Mac Monterey / 12.0.1

**Comment by mouligno** [comment] 2021-11-15 08:57
Closing since we can't reproduce

**Closed by mouligno** 2021-11-15 08:57 UTC
Labels: project: APIM
