### ISSUE TITLE
[service-discovery] [consul] Configure the API endpoint

### ISSUE THREAD

**Issue by kevinimbrechts** [gravitee-io/issues#2104] opened 2019-03-29 09:10 UTC
Hi there.

First of all, sorry to flood you with issues!

I have a little question : I want use Consul as a service discovery with Gravitee. To do this, I need to fill some fields: Consul.io URL, service, DC and ACL. But I think a field is missing: the API endpoint.

### Expected Behavior
In my case, my APIs endpoints looks like this : http://ms-clients/clients/api. For example, in the "Endpoints" screen, I have a default target http://ms-clients/clients/api.
I would like a field to add the API endpoint `/clients/api`.

### Current Behavior
However, if I configure my group with a service discovery (Consul.io), I think it's impossible for me to add `/clients/api`: 
- Consul.io URL: http://consul.services.net:8500
- Service: ms-clients-80
- DC: dc1
- ACL: {my acl}

So when I call the API, like with a GET, Gravitee call http://172.17.0.2:80/adresses instead of http://172.17.0.2:80/clients/api/adresses

### Steps to Reproduce (for bugs)
1. Edit an API
2. Go to Proxy > Endpoints > Group configuration
3. In "Service Discovery", there is no way to add the API endpoint

### Your Environment
* Version used: 1.24.0 (with Docker)

**Comment by brasseld** [comment] 2019-03-29 09:29
As a workaround, I suppose you can make use of dynamic-routing policy?

**Comment by kevinimbrechts** [comment] 2019-03-29 10:08
Hi @brasseld.
For now, my workaround is to redirect `/` to `/xxxx/api/`.
I didn't know dynamic-routing policy with Gravitee. I'll look at this ! Thanks.
The link for posterity : https://docs.gravitee.io/apim_policies_dynamic_routing.html

**Comment by brasseld** [comment] 2019-03-29 10:15
Ok, perfect.

Keeping this issue in opened state because this is something we can add in consul configuration to handle such case.

Regards,

**Comment by kevinimbrechts** [comment] 2019-03-29 10:30
Yes, sure !

**Comment by kevinimbrechts** [comment] 2019-03-29 11:00
Mmmmh it seems like it's not working with Consul ? I see that we can chose an endpoint with "{#endpoints['default']}/{#group[0]}", but how to choose the service discovery ?

**Comment by brasseld** [comment] 2019-03-29 12:30
Service discovery is configured for a given group, let's say "my-group" where "my-group" is the name of the group.

You can apply routing to `{#endpoints['my-group']}/{#group[0]}"` and it will forward calls to endpoints discovered thanks to consul.

Really easy, no ? :-P

**Comment by kevinimbrechts** [comment] 2019-03-29 12:34
Oh sorry, I was not sure about that :)
Thanks.

**Comment by wenwenbaba** [comment] 2019-07-18 10:11
Sorry, I have to use Google Translate to ask you.
I have configured the service discovery for my group and activated it, but I don't know how to fill in the target. I think the serviceId should be filled in here to find it via consul.
So what should this scheme be? Lb:// or consul:?
I have tried it, it didn't work. . .
I only see the implementation class of the endpoint has the http protocol.
盼复为感：）

**Comment by brasseld** [comment] 2019-07-18 10:30
hi @wenwenbaba 

you just have to configure service discovery for your endpoint group (wheel engine icon next to the group name).

**Comment by brasseld** [comment] 2019-07-18 10:43
Ok, this configuration sounds good to me.

What's going wrong there?

**Comment by wenwenbaba** [comment] 2019-07-18 10:52
I continue to use pictures to illustrate。

![image](https://user-images.githubusercontent.com/38455727/61451908-1e93db00-a98d-11e9-8740-fcf9f17e1982.png)
![image](https://user-images.githubusercontent.com/38455727/61451931-2bb0ca00-a98d-11e9-8cdc-df4758b3b370.png)

**Comment by wenwenbaba** [comment] 2019-07-18 11:09
First of all, I admit that the target is filled in incorrectly. It requires a scheme.

![image](https://user-images.githubusercontent.com/38455727/61452741-0cb33780-a98f-11e9-977e-a8203c8a5602.png)

**Comment by aelamrani** [comment] 2019-07-18 11:10
You do not need to fill endpoint configuration if you want to use service discovery, endpoints will be discovered automatically...

**Comment by wenwenbaba** [comment] 2019-07-18 11:21
@aelamrani  
Thank you very much for your reply
I tried to delete all the endpoints in my group.
But it still can't work

![image](https://user-images.githubusercontent.com/38455727/61453271-420c5500-a990-11e9-9ee2-b6bd9dc83074.png)

**Comment by aelamrani** [comment] 2019-07-18 11:24
What did you try? How can you say it does not work? Do you have any error to share?
Can you share the logs of the gateway?

**Comment by wenwenbaba** [comment] 2019-07-18 11:32
I only configure the group now and have configured service discovery for my group.
I deleted all the endpoints.
I even restarted the gateway and management-api.
But the gateway no longer outputs any logs.

When I request this api, the response code is 503.

**Comment by aelamrani** [comment] 2019-07-18 11:34
ok you should find information about the discovery on the logs, please check

**Comment by wenwenbaba** [comment] 2019-07-18 11:47
You are really great.
It is a problem caused by my hand.
I unzipped gravitee-service-discovery-consul-1.1.0.zip into the lib directory.
I am very sorry, bothering the two for so long, to rule out such a low-level mistake for me.
thank you all.
@aelamrani  @brasseld

**Comment by brasseld** [comment] 2020-07-21 07:41
Closed by https://github.com/gravitee-io/issues/issues/3294

**Closed by brasseld** 2020-07-21 07:41 UTC
Labels: project: APIM, type: feature
