### ISSUE TITLE
[management] members are not refreshed when a group is added

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#1084] opened 2018-02-16 08:13 UTC
1. create a group with a user inside
2. add this group to an api and save
3. go to the `members` menu
4. you don't see the group
5. press F5
6. the group appears

**Comment by brasseld** [comment] 2018-04-26 12:13
Duplicate of https://github.com/gravitee-io/issues/issues/1218

**Closed by brasseld** 2018-04-26 12:13 UTC
Labels: type: bug
