### ISSUE TITLE
[gateway] blue/green api deployment

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#935] opened 2017-12-08 13:41 UTC
### Expected Behavior
hot deploy the api config updates

### Current Behavior
When you change the api configuration and deploy it, the gateway unload the previous config and load the new one.
The consequence is that during this process, the api is unreachable.

### Possible Solution
A "blue/green" deployment means deploy the new configuration without expose the config until the deployment is ok, and then redirect all new incoming request to the new api without killing the existing one.

**Comment by brasseld** [comment] 2018-02-24 10:12
Duplicate of #1052

**Closed by brasseld** 2018-02-24 10:12 UTC
Labels: type: feature
