### ISSUE TITLE
[console] PUT request updates the page only with the second call

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6821] opened 2021-12-28 16:32 UTC
## :collision: Describe the bug
After a page is created for the Portal Documentation when using PUT after to update the page it updates the page on second PUT call and on the first the response is 204 No Content while there is one.

## :sunrise_over_mountains: To Reproduce
1. Create/Import simple API.
2. Use Postman to POST a page - > `http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/portal/pages` with example body:

{
    "name" : "Test Page",
    "type": "MARKDOWN",
    "content" : "# (Create page): Test Test Content",
    "published": true,
    "visibility": "PUBLIC",
    "lastContributor": "string",
    "homepage": false
}

3. Get the ID from the Response and open a new tab in Postman and use PUT to update the same page -> `http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/portal/pages/<PageID>` with example body

{
    "name" : "Test Page",
    "content" : "# (Create page): Test Test Content - First Put call from Postman",
    "lastContributor": "test",
    "order": 15,
    "published": true,
    "visibility": "PUBLIC"
}

4. The first response will be 204.

![image](https://user-images.githubusercontent.com/57534152/147586854-49e64d42-9ec5-4ecf-bdf5-77cc2a7e6421.png)

5. Then if you try again it will be okay.

![image](https://user-images.githubusercontent.com/57534152/147586907-7bd7ff89-b5dc-4c49-914f-770ecde82b4f.png)

## :rainbow: Expected behavior
We should be able to update a page with PUT on the first try.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop :

***Please complete the following information:***
 - OS: Windows 10
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***

- 3.8.3

**Comment by mouligno** [comment] 2021-12-28 16:56
Couldn't reproduce on 3.10.x env, I close the issue since 3.8 is no longer supported

**Closed by mouligno** 2021-12-28 16:56 UTC
Labels: type: bug, project: APIM, Support 2
