### ISSUE TITLE
[packaging] keep config files when upgrading with rpm

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5287] opened 2021-03-23 17:03 UTC
If I update a gravitee installation with yum, all config files disappered.
### Your Environment

* Version used: 1.30, 3.5

**Comment by mouligno** [comment] 2021-12-31 08:41
@brasseld  Can we close this issue ?

**Comment by brasseld** [comment] 2021-12-31 10:01
If you think that it's been fixed, yes. But I'm not sure who fixed it. I don't see changes from scripts.

**Comment by apoddany** [comment] 2022-02-16 10:05
The issue is still there when upgrading from 3.10 to 3.15
When doing the "yum update" command, the config/gravitee.yml is not kept but replaced by a clean one but also removed from the previous installation.
1. Do not remove the config/gravitee.yml and rename it as (ie) .backup file instead
2. Keep the original config/gravitee.yml file from previous install to the new install

**Closed** 2022-06-17 09:24 UTC
Labels: type: bug, project: APIM, project: AM, Support 2, p3, loop quantum
