### ISSUE TITLE
[management] ExceptionInInitializerError while upgrading jdk to 11

### ISSUE THREAD

**Issue by bkhadige** [gravitee-io/issues#2481] opened 2019-07-22 11:29 UTC
ExceptionInInitializerError while starting management-api using java 11

### Expected Behavior

...
**### org.apache.commons.**### lang3**.time.FastDateFormat.getInstance(FastDateFormat.java:119)**

### Current Behavior

Error creating bean with name 'logsServiceImpl' defined in URL [jar:file:.../gravitee-management-api-service-1.28.0.jar!/io/gravitee/management/service/impl/LogsServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError

### Possible Solution

- looks related to : https://issues.apache.org/jira/browse/LANG-1285
- upgrade the jar version to **### commons-lang3-3.9.jar** solved the problem

### Steps to Reproduce (for bugs)

1. use jre-11-openjdk-11.0.1.13-3.el7_6.x86_64

### Context

- Upgrade Java version from 8 to 11

### Your Environment

* Version used: 1.28.0
* Browser Name and version:
* Operating System and version: rhel 7.6

**Comment by brasseld** [comment] 2019-09-20 14:20
Closed by https://github.com/gravitee-io/gravitee-management-rest-api/commit/55aa31abc4da8deea3dad498de75988b2f69199a

**Comment by julienfradillon** [comment] 2019-10-01 08:20
Hi, I have always a problem when I try APIM 1.29.1 whis java 11:

> 17:19:08.214 [graviteeio-node] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alertTriggerServiceImpl': Unsatisfied dependency expressed through field 'apiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiServiceImpl': Unsatisfied dependency expressed through field 'eventService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventServiceImpl': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'applicationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationServiceImpl': Unsatisfied dependency expressed through field 'subscriptionService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subscriptionServiceImpl' defined in URL [jar:file:/opt/mdsa358/graviteeio-management-api-1.29.1/lib/gravitee-management-api-service-1.29.1.jar!/io/gravitee/management/service/impl/SubscriptionServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError

**Comment by brasseld** [comment] 2019-10-01 08:28
Please provide the complete stack trace.

**Comment by julienfradillon** [comment] 2019-10-01 08:59
Oct  1 09:26:15 intapigra-vli01 gravitee: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'alertTriggerServiceImpl': Unsatisfied dependency expressed through field 'apiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiServiceImpl': Unsatisfied dependency expressed through field 'eventService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventServiceImpl': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'applicationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationServiceImpl': Unsatisfied dependency expressed through field 'subscriptionService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subscriptionServiceImpl' defined in URL [jar:file:/opt/mdsa358/graviteeio-management-api-1.29.1/lib/gravitee-management-api-service-1.29.1.jar!/io/gravitee/management/service/impl/SubscriptionServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
Oct  1 09:26:15 intapigra-vli01 gravitee: at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.node.container.spring.SpringBasedContainer.initializeContext(SpringBasedContainer.java:61)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.node.container.spring.SpringBasedContainer.initialize(SpringBasedContainer.java:51)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.node.container.AbstractContainer.<init>(AbstractContainer.java:41)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.node.container.spring.SpringBasedContainer.<init>(SpringBasedContainer.java:44)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.management.standalone.ManagementContainer.<init>(ManagementContainer.java:27)
Oct  1 09:26:15 intapigra-vli01 gravitee: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Oct  1 09:26:15 intapigra-vli01 gravitee: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Oct  1 09:26:15 intapigra-vli01 gravitee: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Oct  1 09:26:15 intapigra-vli01 gravitee: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
Oct  1 09:26:15 intapigra-vli01 gravitee: at java.base/java.lang.Class.newInstance(Class.java:584)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.management.standalone.boostrap.Bootstrap.init(Bootstrap.java:56)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.management.standalone.boostrap.Bootstrap.start(Bootstrap.java:158)
Oct  1 09:26:15 intapigra-vli01 gravitee: at io.gravitee.management.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
Oct  1 09:26:15 intapigra-vli01 gravitee: Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiServiceImpl': Unsatisfied dependency expressed through field 'eventService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventServiceImpl': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'applicationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationServiceImpl': Unsatisfied dependency expressed through field 'subscriptionService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subscriptionServiceImpl' defined in URL [jar:file:/opt/mdsa358/graviteeio-management-api-1.29.1/lib/gravitee-management-api-service-1.29.1.jar!/io/gravitee/management/service/impl/SubscriptionServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError

**Comment by julienfradillon** [comment] 2019-10-01 09:11
[log_javalang3.log](https://github.com/gravitee-io/issues/files/3675358/log_javalang3.log)

**Comment by julienfradillon** [comment] 2019-10-09 12:20
Hi, have you take a look ?

**Closed** 2019-10-16 11:17 UTC
Labels: project: APIM, type: bug
