### ISSUE TITLE
[portal] split configuration menu

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#525] opened 2017-03-31 12:44 UTC
Currently, the `Configuration` menu manages views, sharding tags, tenants, and groups.
With #468 an other configuration item will appears.

It can be useful to split the config menu between portal configuration and platform configuration.

Platform Cfg :
 - sharding tags
 - tenants

Portal Cfg : 
 - views
 - groups
 - pages

**Comment by brasseld** [comment] 2018-02-23 14:04
Duplicate of #1101

**Closed by brasseld** 2018-02-23 14:04 UTC
Labels: type: enhancement
