### ISSUE TITLE
Improve API Import page

### ISSUE THREAD

**Issue by ctschacher** [gravitee-io/issues#7321] opened 2022-03-17 10:56 UTC
There are several issues with the current Import page. Filing a bug report for every issue might be unnecessary, instead we probably want to re-design the whole import page, including a better UX?

**Bugs**
- After trying to import a faulty swagger file (empty or malformed) it's not possible to import a different file
- Providing an empty, malformed file or not existing URL returns a status 500 together with an not very user friendly error message (`Cannot invoke \"io.swagger.v3.oas.models.OpenAPI.getComponents()\" because \"openAPI\" is null`)
 -> I would expect something in the 4xx with a clear error message 

**Design**
- The page for `IMPORT File` and `IMPORT FROM LINK` looks different & there almost nothing to see for the file import, why not just having everything on one page and maybe toggle between the two options (by sth like radio buttons maybe)
- There a 2 different kind of error messages: one appears as a temporary red box in the lower right corner (e.g. if swagger can not be parsed correctly) and the other one as a permanent red writing on the screen just below the import input field ( e.g. if using a wrong link for swagger import via link)

### Steps to Reproduce (for bugs)
1. Go to API import

### Your Environment
* Version used: 3.16.1
* Browser Name and version: Chrome
* Operating System and version: MacOS

**Comment by mouligno** [comment] 2022-04-01 12:49
duplicate of https://github.com/gravitee-io/issues/issues/6663

**Closed by mouligno** 2022-04-01 12:49 UTC
Labels: type: enhancement, type: bug, project: APIM
