### ISSUE TITLE
[PORTAL] Shared API Key Renew/Revoke confirmation popup design does not match

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#7322] opened 2022-03-17 12:10 UTC
when the user clicks on RENEW/REVOKE, the confirmation popup that is displayed doesnt have the same design

### Expected Behavior
confirmation popup should have the same design

### Current Behavior
confirmation popup that is displayed doesnt have the same design

### Steps to Reproduce (for bugs)
1. go to https://apim-master-portal.cloud.gravitee.io/
2. select an application that has shared api key
3. go to subscriptions
4.click on RENEW and then REVOKE
5. notice the popup design
![Screenshot 2022-03-17 at 12.09.02.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/f5443ae1-605b-41da-a99d-5a7040923e54)![Screenshot 2022-03-17 at 12.09.07.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/fad385a9-4bbb-430d-8449-6e0c5942bfe3)

### Your Environment
* Version used: https://apim-master-portal.cloud.gravitee.io
* Browser Name and version: google Chrome Version 99.0.4844.51 (Official Build) (x86_64)
* Operating System and version: MacOS Monterey 12.2.1 (21D62)

**Comment by RubenMMSantos** [comment] 2022-03-17 12:15
Same issue for the confirmation popup when trying to close a subscription on application side in Portal
![Screenshot 2022-03-17 at 12.14.29.png](https://images.zenhubusercontent.com/612518f668e84e3f309d282d/c429a48f-491e-4030-91fc-cbb115e3751b)

**Comment by phiz71** [comment] 2022-03-17 13:46
For me it's not a bug. As closing a subscription or revoking keys are critical action, the confirm message is in orange to warn the user.
Whereas the renew is a classical confirmation message

**Closed** 2022-03-18 09:04 UTC
Labels: project: APIM, type: uat, loop quantum
