### ISSUE TITLE
Error message for trying to import an existing API schema does not go away if another, valid one is selected

### ISSUE THREAD

**Issue by lju-lazarevic** [gravitee-io/issues#6968] opened 2022-01-18 17:38 UTC
## :collision: Describe the bug
Error message for trying to import an existing API schema does not go away if another, valid one is selected

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1 - Go to APIs
2 - Click + and select Import
3 - Select an API definition that has been previously imported
4 - Select another API definition that has not been imported

## :rainbow: Expected behaviour
Error message should go away if valid definition has been selected

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/30664797/149989396-a1fe01f0-e521-4e17-bc50-b620dc00e5df.png)

## :computer: Desktop :

***Please complete the following information:***
 - Windows 10
 - Edge

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment] 2022-01-25 09:36
Closed since it's duplicate of https://github.com/gravitee-io/issues/issues/6663

**Closed by mouligno** 2022-01-25 09:36 UTC
Labels: project: APIM, type: uat
