### ISSUE TITLE
[management] Template missing PORTAL.USER_CREATED

### ISSUE THREAD

**Issue by Subbu0117** [gravitee-io/issues#2669] opened 2019-09-24 08:08 UTC
When Gravitee admin created user below exception thrown. Please add PORTAL.USER_CREATED.ym to the notifications/portal directory. 

Exception:
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "notifications/portal/PORTAL.USER_CREATED.yml".

Thanks

**Comment by Subbu0117** [comment] 2019-10-21 09:56
@NicolasGeraud , as discussed I created above issue. please map it to a release.

**Comment by aelamrani** [comment] 2019-10-22 06:40
@Subbu0117 Are you interested in providing a pull request for this?

**Comment by brasseld** [comment] 2019-10-25 08:06
I remove the `more-information-needed` since we don't want the issue to be closed automatically by the bot... this is still a bug...

**Comment by aelamrani** [comment] 2019-10-25 08:20
Bad reflex

**Comment by brasseld** [comment] 2020-06-01 21:36
Duplicate of https://github.com/gravitee-io/issues/issues/3168

**Closed by brasseld** 2020-06-01 21:36 UTC
Labels: project: APIM, type: bug
