### ISSUE TITLE
[gateway] conditional logging on date/Duration prevents to display API logs

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7351] opened 2022-03-22 10:23 UTC
## :collision: Describe the bug
When enabling logging on an API with a Condition on an date/Duration, the detailed logs are not displayed and the following warning is raise in the gateway logs :
```
gio_apim_gateway-3.16.1 | 10:17:52.956 [vert.x-eventloop-thread-4] [] WARN  i.g.g.c.l.p.LoggableRequestProcessor - Unexpected error while evaluating logging condition for the API e410fbd5-725e-43b5-90fb-d5725ea3b5e0 and context path /echo/ : EL1041E: After parsing a valid expression, there is still more data in the expression: 'Mar'
``` 
Condition is displayed as : 
{#request.timestamp <= Fri Mar 25 2022 14:00:15 `GMT+0100l}

Workaround is to convert to a timestamp in Milliseconds as : 
{#request.timestamp <= 1647944975000l}

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Create an API with API Key Plan
2. subscribe to it with your Default Application
3. Enable Logging on the API and add a Condition on the Date/Duration
4. Make a request on the API and check the logs

## Current behaviour
A clear and concise description of what is currently happening.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.16.1

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

see also https://github.com/gravitee-io/issues/issues/7329

Link a story or other related things...

**Comment by gaetanmaisse** [comment] 2022-04-29 11:53
Per the documentation (https://docs.gravitee.io/apim/3.x/apim_publisherguide_expression_language.html#request) `request.timestamp` is a Long and so the right part of your expression must be a Long too. So having an ISO string date can't work.

**Comment by gaetanmaisse** [comment] 2022-04-29 11:54
Closing as it's not a bug/reg.

**Comment by apoddany** [comment] 2022-05-31 10:15
Reopening this as re-tested in latest 3.17.3.
When configuring logging at the API level and add a Condition on the Date/Duration with the "Logging Condition Editor" (pen icon) and select an End Date or Duration, the UI will set it up as : 
```
{#request.timestamp <= Fri Jul 01 2022 00:00:11 `GMT+0200l}`
```
No more exception in the logs but the detailed logs for the API won't be displayed in the UI

<img width="1192" alt="Capture d’écran 2022-05-31 à 12 13 57" src="https://user-images.githubusercontent.com/79909781/171150770-0359a990-fb57-459f-9cd4-eac104f384ed.png">

**Comment by gaetanmaisse** [comment] 2022-06-03 10:27
The popup has been reworked technically so it will be great to deeply tests the interaction in it to be sure no regression were introduced

**Comment by LiliaEn** [comment] 2022-06-10 07:25
Tested on 3.16.x
Browser: Chrome Version 99.0.4844.74 , macOS Big Sur v11.6
Working as expected

**Closed by LiliaEn** 2022-06-10 07:25 UTC
Labels: type: bug, project: APIM, Support 2, p2, loop quantum, status: in test
