### ISSUE TITLE
Plan name override other plan if too long.

### ISSUE THREAD

**Issue by mathela59** [gravitee-io/issues#1054] opened 2018-02-02 10:24 UTC
When you have two plans on an api, if there's one which have a too long name, the contextual menu of this one is not reachable.

### Expected Behavior
Name should be boxed, Even if it takes two or more lines.

### Current Behavior
Name is displayed but it repeals the configuration button outside of the box

### Steps to Reproduce (for bugs)
1. Create an api
2. Create a first plan with a super long name (ex : abcdefghijklmanopqrstuwxyz1234567890_plantest
3. Create a second plan (name doesn't matter)
4. try to access the configuration button of the first plan.

### Your Environment
* Version used: 1.12.3
* Browser Name and version: Chrome
* Operating System and version: Windows.

**Comment by brasseld** [comment] 2018-02-02 15:45
Duplicate of #1045

**Closed by brasseld** 2018-02-02 15:45 UTC
