### ISSUE TITLE
[management] Top failed APIs shows 100% Failed on 200 status in Application Analytics

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#5703] opened 2021-06-09 16:54 UTC
On Application Analytics, when clicking on the 200 Status in "Response Status" Panel, the "Top failed Apis" panel gets filled with 100% failed for the API.

### Steps to Reproduce (for bugs)

1. Create/deploy an API with a Plan 
2. Create an Application and Subscribe to this API
3. Generate a few calls on the API (with 200 status)
4. Check the Application Analytics
5. Click on "200" Status in "Response Status" Panel
<img width="1752" alt="Capture d’écran 2021-06-09 à 16 56 43" src="https://user-images.githubusercontent.com/79909781/121395816-16fbc780-c953-11eb-969a-eacc65958bd8.png">
6. "Top failed Apis" Panel will show 100% failed for the API

7. Filters will show status = '200'
<img width="1739" alt="Capture d’écran 2021-06-09 à 16 57 09" src="https://user-images.githubusercontent.com/79909781/121396239-72c65080-c953-11eb-838f-25fc27d23ecc.png">

### Your Environment

* Version used: 3.5.12 / 3.5.6
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by mouligno** [comment] 2021-10-05 12:59
Duplicate of #5771, would be fixed in 3.5.19

**Closed by mouligno** 2021-10-05 12:59 UTC
Labels: type: bug, project: APIM, Support 3
