### ISSUE TITLE
[management] Filtering by group id in ApiService works wrong for non-admin users

### ISSUE THREAD

**Issue by faraday-m** [gravitee-io/issues#4512] opened 2020-10-27 11:29 UTC
Management REST API allows getting a list of APIs related to a group using group id in query parameter. It works fine for system admin role but fails on repeating this with custom user role even if user has all priviliges for groups. 

### Expected Behavior
When we're authenticated with non-admin user and are trying to get list of APIs with access from a group, we get list of APIs connected with this group.  

### Current Behavior
APIM response contains not only APIs related to selected group but all public APIs and APIs related to any of user's groups. 

### Possible Solution
Possibly bad logic in ApisResource/ApiServiceImpl: everything works fine for users with MANAGEMENT_ADMIN role. 

### Steps to Reproduce (for bugs)
Prerequisites: some API with association to a group, some public APIs and a user with full rights in management scope but with custom admin role. 
1. Sending GET /management/apis?group={group_id} to APIM with basic user auth as a user with custom role
2. Receive list with all public APIs
3. Sending same request from user with system management_admin role
4. Receive APIs related to requested group

### Your Environment
Release 1.30.5 - seems there still was no issue with same problem

**Comment by jhaeyaert** [comment] 2020-11-02 17:59
Hi @faraday-m, thanks for your report.

I spent some time trying to reproduce this bug with no luck. I see you're using a pretty old version. May I suggest you to retry with the latest 1.30.x version ( currently 1.30.24) ? A lot of things happened since and I think the problem is fixed now (that could explain why I couldn't reproduce the problem you mentioned).

I'll close this issue. Feel free to reopen it if you experiment same problem with the latest 1.30.x.

Thx.

**Closed by jhaeyaert** 2020-11-02 17:59 UTC
Labels: project: APIM, status: in progress, type: bug
