### ISSUE TITLE
[portal] Page names in URL instead of IDs

### ISSUE THREAD

**Issue by radicarl** [gravitee-io/issues#2728] opened 2019-10-08 12:53 UTC
Currently the general documentation and the api documentation are only accessible over the ids of the pages. Because the id are generated you don't get a URL to a page, that is constant over different installations/stages and which do not change if I have to recreate the page.

I think using the ids for administration parts is okay, but not so for the documentation. I want to place links to documentation pages on various sites and tools or send them to consumers of our apis. After a reinstallation or a recreation of a page, all these links are invalid.

### Expected Behavior
* **api-portal.tld/#!/pages/introduction** refers to the documentation page Introduction
* **api-portal.tld/#!/pages/concepts/guide** refers to the documentaiton page Guide in the folder Concepts
* **api-portal.tld/#!/apis/my-cool-api/pages/tutorial** refers to the page named tutorial of the API named "My Cool API"

### Your Environment
* Version used: 1.28.1

**Comment by brasseld** [comment] 2019-10-08 12:58
Duplicate of https://github.com/gravitee-io/issues/issues/2250

**Comment by radicarl** [comment] 2019-10-09 10:15
I think it is not a complete duplicate, because I need it only for the navigation of documents in the portal. In my case, the APIs could still be called with the IDs.

**Comment by aelamrani** [comment] 2020-09-07 06:13
Need to implement Server Side Rendering to have a proper SEO/User friendly solution.

**Closed** 2022-05-28 08:57 UTC
Labels: project: APIM, wontfix
