### ISSUE TITLE
Warning when getting freemarker template

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7037] opened 2022-02-03 08:05 UTC
During startup we are seeing these warning messages in the logs:
```
WARN  i.g.r.a.s.i.NotificationTemplateServiceImpl - Problem while getting freemarker template PORTAL.USER_REGISTRATION_REQUEST from file : /opt/graviteeio-full-3.15.1/graviteeio-apim-rest-api-3.15.1/templates/notifications/portal/PORTAL.USER_REGISTRATION_REQUEST.yml (No such file or directory)
```

This is one of many warnings for missing templates.
The folder is checked and empty. 
In older releases the flies are available.

Used version 3.15.0, 3.15.1

**Comment by brasseld** [comment] 2022-02-03 08:08
Hey @kirestoj01 how are you running gravitee ?

**Comment by kirestoj01** [comment] 2022-02-03 09:02
@brasseld it was on both local and docker installation.

**Comment by phiz71** [comment] 2022-03-18 09:34
Hi, it's the same root cause as https://github.com/gravitee-io/issues/issues/7057
It has been fixed in 3.15.3

**Comment by ytvnr** [comment] 2022-03-23 15:02
so can we close it ?

**Comment by gaetanmaisse** [comment] 2022-06-15 17:59
Closing as it has been fixed with https://github.com/gravitee-io/issues/issues/7057, released in 3.15.3

**Closed by gaetanmaisse** 2022-06-15 17:59 UTC
Labels: type: bug, project: APIM, Support 3, p4
