### ISSUE TITLE
[themes] Issue with Theme on multiple environments, one theme for both

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#8541] opened 2022-09-29 10:23 UTC
## :collision: Describe the bug
If we have multiple environments in APIM-Cockpit and we try to set a separate theme on both we only get one, every change made on the themes overwrites the previous change

## :sunrise_over_mountains: To Reproduce
1. Make sure you have APIM connected to Cockpit to set up a multiple environment.
2. Change the theme on first env. then change the theme on the second env.
3. You will see that the second env overwrote the change on the first env.
4. There is only one record in the DB also.

## :rainbow: Expected behavior
To be able to change themes on all env. without them overwriting the previous change.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop 3.18.7
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.18.X

**Comment by gaetanmaisse** [comment] 2023-01-18 07:59
Closing as duplicate of https://github.com/gravitee-io/issues/issues/8820, the fix will be available in APIM 3.21.0

**Closed by gaetanmaisse** 2023-01-18 07:59 UTC
Labels: type: bug, project: APIM, cockpit & multi-env, Support 3, p2
