### ISSUE TITLE
Intended Users of gravitee are not able configure and use override options for all the mentioned points 

### ISSUE THREAD

**Issue by bobvamsidhar7775** [gravitee-io/issues#4703] opened 2020-12-01 07:49 UTC
1 | How and where   to define environment variables to override system properties and   gravitee.yml. similarly where to define system properties to override   gravitee.yml  - Component - APIM Gateway
2 | how   and where to configure web socket and web socket secure protocol for   consuming the API which was published as per point "Enable web socket   support" - Component - APIM Gateway
3 | how   and where to configure plugins repository for APIM Gateway plugins directory - Component -  APIM Gateway
4 | how   and where to define end points for APIM API ie Get /_node,Get   /_node/health,Get/_node/Configuration - Component -  APIM API (Internal   API)
5 | how   and where to customise the API portal theme or console.where to access the   portal to configure portal URL is not defined - Component -  APIM Portal
6 | In   APIM portal installation     
 - It was mentioned  Run APIM portal       
 - APIM portal is based on nginx      
- There is no where mentioned where to access APIM portal in documentation | APIM   Portal installation through Redhat

**Comment by brasseld** [comment] 2020-12-01 07:53
The issue is not relevant here. It could be easier for us to manage a set of different issues instead of one with multiple point.

Closing the issue.

**Closed by brasseld** 2020-12-01 07:53 UTC
