### ISSUE TITLE
[gateway] No Handler can be found for request /, returning NOT_FOUND (404)

### ISSUE THREAD

**Issue by newmoon88** [gravitee-io/issues#3217] opened 2020-02-12 13:15 UTC
Hi,
I have set up Gravitee .io  from the docker Images provided on the official site on my local Windows machine.
After executing:
docker-compose -f docker-compose-local.yml up
from the command prompt, everything seems fine. 

But when I perform a get request on the gateway url, namely: "http://localhost:8000/"
From the browser I get: "No context-path matches the request URI."
And from the command prompt I see the warning: "No Handler can be found for request /, returning NOT_FOUND (404)"

Any help is really appreciated :)

**Comment by brasseld** [comment] 2020-02-12 23:23
Did you deploy an API to the API Gateway?

**Comment by newmoon88** [comment] 2020-02-13 08:23
Yes, I deployed a first API.
The problem is that when I make a call with my browser to the "<gateway_url>/context_path" my API , that is located at the backend url that I specified, doesn't get called. 
In fact I get 502 bad gateway and in the api call I get "Connection refused: localhost/<localhost_IP>:<my_backendapi_port>".

The backend is hosted on IIS locally on my computer; namely I run my backed API through Visual Studio.

**Comment by brasseld** [comment] 2020-02-13 08:41
So it means that the gateway can't reach your backend.

Check your network or perhaps you have defined HTTPS (in that case, do not forget to enable trust all).

**Comment by newmoon88** [comment] 2020-02-13 08:45
As regards the network I am connected to my company network, should I switch to another network e.g.  use my mobile as hotspot?

As regards the https, yes my backend api has an URL starting with https, what do you mean by enabling trust all?

Thank you for your quick answer

**Comment by brasseld** [comment] 2020-02-13 09:03
From endpoint configuration -> enable Trust all (SSL section).

**Comment by newmoon88** [comment] 2020-02-13 09:19
![image](https://user-images.githubusercontent.com/60968730/74419401-1f6cec80-4e4a-11ea-93b2-1b5bb84f3943.png)
I configured "trust all " from the Proxy--> Endpoints -->SSL but with no success.

**Comment by brasseld** [comment] 2020-02-13 09:22
Sorry but the title of the issue is `No Handler can be found for request /, returning NOT_FOUND (404)` and now we're speaking about 502 error.

So what's the real issue here?

**Comment by newmoon88** [comment] 2020-02-13 09:24
I noticed that in the exported json file with all the configuration, I have "proxyenabled set to false":


[TestWeatherApi-1 _AllConfig.txt](https://github.com/gravitee-io/issues/files/4197436/TestWeatherApi-1._AllConfig.txt)

**Comment by brasseld** [comment] 2020-02-13 09:26
You just have a network issue between the gateway running inside a docker container and the backend which is running on your local machine.

This is not relative. By default the docker container is not able to reach the docker host. Please check the docker documentation.

**Comment by newmoon88** [comment] 2020-02-13 09:28
At the beginning I thought it was an issue with the gateway. Then reading your comments I figured out it is an issue as regards the call to the backend.
thank you for the answers you provided me and I hope I still can get support.

For sure I will go through the documentation and double check my configurations.

**Comment by brasseld** [comment] 2020-02-13 09:34
Ok, I'm closing the issue.

**Closed by brasseld** 2020-02-13 09:34 UTC
Labels: project: APIM
