### ISSUE TITLE
[kubernetes] deprecated k8s APIs

### ISSUE THREAD

**Issue by l-lin** [gravitee-io/issues#2835] opened 2019-11-04 09:31 UTC
Since Kubernetes 1.16, some deprecated APIs have been removed in favor of newer and more stable API versions.

Please check https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

### Possible Solution

```bash
sed -i 's~apps/v1beta1~apps/v1~g' apim/templates/*deployment.yaml
sed -i 's~extensions/v1beta1~networking.k8s.io/v1beta1~g' apim/templates/*ingress.yaml
```

PR: https://github.com/gravitee-io/helm-charts/pull/30

### Steps to Reproduce (for bugs)

1. Have a kubernetes in version 1.16+
2. Try to deploy the APIM helm charts
3. Kubernetes will throw the following error:

```
error: unable to recognize "STDIN": no matches for kind "Deployment" in version "apps/v1beta1"
```

### Your Environment

* Helm chart version used: 1.27.2
* Kubernetes version: 1.16.2

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-04-27 15:32
Hi, I haven't tried the fix yet (on the way to), but : 
* I have reproduced the exact same issue (my top error in error stack, is about `v1-beta1 blabla...`, 
* But I want to mention, that it looks like I am running `Kubernetes` vversion **less than `1.16`** : 

```bash
# see https://github.com/gravitee-io/issues/issues/2835

jbl@poste-devops-jbl-16gbram:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
jbl@poste-devops-jbl-16gbram:~$ 
```
* Before I bring in more data to reproduce : has anyone exeprienced the same (I'm on AWS)  ?

Oh, I have an idea : Oh gosh, they comile their own Kubernetes from source, and they have a different, shifted version numbering at AWS, for their Kubernetes Amazon Distribution : 

`GitVersion:"v1.15.11-eks-af3caf`

see the `eks` ? that's an Amazon issued COMMIT ID .

So my guess is that Amazon Distrib. Kubernetes version `1.15` (`v1.15.11-eks-af3caf`), actually is compatible with a version of the real Kubernetes, above `1.16`

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-04-30 12:16
Hi @l-lin just an obviousupdate, for the sake of helping eeasing up  the future reader's journey : 

```bash 
root@f1e19bc8161b:/pulumi/lab/manuel.helm# ls -allh
total 48K
drwxr-xr-x 5 root root 4.0K Apr 30 12:12 .
drwxr-xr-x 8 root root 4.0K Apr 30 11:56 ..
drwxr-xr-x 8 root root 4.0K Apr 30 11:54 .git
-rw-r--r-- 1 root root  100 Apr 30 11:54 .gitignore
-rw-r--r-- 1 root root   16 Apr 30 11:54 CNAME
-rw-r--r-- 1 root root 3.4K Apr 30 11:54 CONTRIBUTING.adoc
-rw-r--r-- 1 root root  12K Apr 30 11:54 LICENSE.txt
-rw-r--r-- 1 root root 1.2K Apr 30 11:54 README.md
drwxr-xr-x 4 root root 4.0K Apr 30 11:59 am
drwxr-xr-x 3 root root 4.0K Apr 30 11:54 apim
root@f1e19bc8161b:/pulumi/lab/manuel.helm# sed -i 's~apps/v1beta1~apps/v1~g' apim/templates/**/*deployment.yaml
root@f1e19bc8161b:/pulumi/lab/manuel.helm# sed -i 's~extensions/v1beta1~networking.k8s.io/v1beta1~g' apim/templates/**/*ingress.yaml
root@f1e19bc8161b:/pulumi/lab/manuel.helm# git remote -v
origin	git@github.com:gravitee-io/helm-charts (fetch)
origin	git@github.com:gravitee-io/helm-charts (push)
root@f1e19bc8161b:/pulumi/lab/manuel.helm# git log --name-status HEAD^..HEAD
commit 6089b683558aa268cc8ec51b3abe3ed4b8636f37
Author: Gustavo Valverde <gustavo@iterativo.do>
Date:   Tue Mar 10 22:08:24 2020 -0400

    [FIX] apim: Use correct service values for mongo and elasticsearch
    
    When installing using helm, mongo and elasticsearch services uses the helm name used in the README, which is: `graviteeio-apim`

M       apim/values.yaml
root@f1e19bc8161b:/pulumi/lab/manuel.helm# 

```

**Comment by brasseld** [comment] 2020-08-26 10:29
Hello there,

I'm closing the issue as latest charts are now compatible with 1.16.

**Closed by brasseld** 2020-08-26 10:29 UTC
