### ISSUE TITLE
[policy] bump Policy HTTP Callout version to 1.15.1 to fix accented content issues 

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8357] opened 2022-08-25 12:12 UTC
See https://github.com/gravitee-io/issues/issues/8109

**Comment by patelami** [comment] 2022-09-01 08:27
This is duplicate of https://github.com/gravitee-io/issues/issues/8235#issue-1322017484

**Closed by patelami** 2022-09-01 08:27 UTC
Labels: type: technical, project: AM
