### ISSUE TITLE
When a certain method is preselected in a Flow Configuration, it is not possible to remove it and leave the field empty in order to apply the configuration to ALL methods.

### ISSUE THREAD

**Issue by LiliaEn** [gravitee-io/issues#6024] opened 2021-08-20 16:17 UTC
When a certain method is preselected in a Flow Configuration, it is not possible to remove it and leave the field empty in order to apply the configuration to ALL methods.

### Expected Behavior
When removing the existing methods in a flow, it should be possible to save the changes and the changes should be applied. It should be possible to leave Methods field empty in order to apply the configuration to ALL methods.

### Current Behavior
When existing methods are removed, Save button doesn't get enabled all the time. When it gets enabled and it is possible to click it, the changes are not applied. It is not possible to leave Methods field empty. Please see the video attched: https://drive.google.com/file/d/1P1EupsYSEUlFyYwYHB4AbINzck3wzFaa/view?usp=sharing

### Steps to Reproduce (for bugs)
1. Import/Create and API or use an existing one
2. Go to Design tab
3. Select a Flow that has a single or multiple methods (not ALL)
4. Remove all methods
5. Save the changes
6. Check if the changes were applied.

### Your Environment
https://nightly.gravitee.io/
* Version used:
* Browser Name and version: Chrome Version 91.0.4472.114
* Operating System and version: MacOS Big Sur, Version 11.5

**Comment by mouligno** [comment] 2022-03-14 16:58
Duplicate of #6422

**Closed by mouligno** 2022-03-14 16:58 UTC
Labels: type: bug, project: APIM
