### ISSUE TITLE
Error in management console

### ISSUE THREAD

**Issue by LjupchoKostoski** [gravitee-io/issues#6581] opened 2021-11-17 11:58 UTC
- Description
  - In API > Pages  "Failed to load API definition" error is shown when “Show the URL to download the content” option is enabled
  - It adds a ' at the end of the API definition URL preventing to access it

With unchecked option:

![1](https://user-images.githubusercontent.com/89591105/142207595-07e939a4-662a-4533-aadd-48db93cb8976.PNG)
![2](https://user-images.githubusercontent.com/89591105/142207240-2a78ce77-9228-444b-9ad1-2c4783a8559c.PNG)

With checked option:

![3](https://user-images.githubusercontent.com/89591105/142207652-d9479928-7544-4ab8-89be-a6b3687cfee4.PNG)
![4](https://user-images.githubusercontent.com/89591105/142207251-b7bd2a5e-b60e-4118-a308-035dd0a47de3.PNG)

- Environment
  - Version used: 3.10.4
  - Browser Name and version: Chrome
  - Operating System and version: Docker Desktop

**Comment by marijatimovska** [comment] 2022-02-18 11:04
Duplicate of https://github.com/gravitee-io/issues/issues/6713.
I will close this one.

**Closed by marijatimovska** 2022-02-18 11:04 UTC
