### ISSUE TITLE
Save banner is displayed even without any modifications

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#7109] opened 2022-02-14 15:15 UTC
## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to Design menu of an API
2. Click on Portal menu item
3. Come back to Design screen
4. See the banner

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment] 2022-02-15 08:29
Closing as duplicate of https://github.com/gravitee-io/issues/issues/7105

**Closed by gaetanmaisse** 2022-02-15 08:29 UTC
Labels: project: APIM, type: uat, dark matter
