### ISSUE TITLE
[portal] save button remains disabled when setting http proxy

### ISSUE THREAD

**Issue by AnselmeDewavrin** [gravitee-io/issues#414] opened 2017-01-16 17:07 UTC
For a freshly created api, it's impossible to save the http proxy settings because the save button is disabled

### Expected Behavior

when changing the http proxy settings the save button should turn enabled

### Current Behavior

ui save button remains disabled when setting http proxy

### Steps to Reproduce (for bugs)

1. create an api
2. change the http proxy settings

### Context

workaround : deploy

### Your Environment

* Version used: 1.2
* Browser Name and version: FF and chrome
* Operating System and version: win10 and macos

**Comment by aelamrani** [comment] 2017-01-16 17:12
Hello,

I'm not able to reproduce your issue. 

On the step 2 you just check the HTTP Proxy checkbox or also fill the  required fields (type, valid host and port)?

**Comment by brasseld** [comment] 2017-01-16 20:52
For step 2, please enable "HTTP proxy" and then, set a host / port for proxy.
The _save_ button is still disabled.

**Comment by brasseld** [comment] 2017-01-30 20:40
`save`button is disabled because some required fields are not filled.

Closing this issue.

**Closed by brasseld** 2017-01-30 20:40 UTC
Labels: type: bug, type: wontfix
