### ISSUE TITLE
Restart UI Container leads to HTTP 301

### ISSUE THREAD

**Issue by nicomanzoni** [gravitee-io/issues#9186] opened 2023-08-17 10:01 UTC
## Describe the bug

When installing APIM Version 4 on docker and restarting the Console UI or Portal UI container, after the restart trying to access either one leads to a HTTP 301 message and redirects to an empty page on port 8080\. It is not dependant on the exposed Ports of the Console or Portal.

## To Reproduce

Steps to reproduce the behaviour:

1.  Install APIM Version 4 with docker-compose, either [Quick Install](https://docs.gravitee.io/apim/3.x/apim_installation_guide_docker_compose_quickstart.html) or [Custom Install](https://docs.gravitee.io/apim/3.x/apim_installation_guide_docker_compose.html)
2.  Start the compose with docker-compose
3.  Restart the gio_apim_management_ui container with docker restart gio_apim_management_ui
4.  Access Console UI on web

## Expected behaviour

The Console UI loads normally.

## Current behaviour

The request returns the HTTP message 301 "Moved permanently" and redirects to Port 8080, where no connection can be established.

## Useful information

[<span class="image-wrap" style="">![](https://github.com/gravitee-io/issues/assets/142493492/9c83bd2f-f04e-4d3b-bdf5-2cd9bc08af8d)</span>](https://github.com/gravitee-io/issues/assets/142493492/9c83bd2f-f04e-4d3b-bdf5-2cd9bc08af8d) This issue occurs only with APIM Version 4\. Tested on 3.20.xx and works as expected.

## Environment

Docker version 24.0.2 APIM Version 4, image tag 4.

**Comment by gaetanmaisse** [comment] 2023-08-29 12:47
Did you try with the latest version of APIM 4.0? I recall some fixes on that side, so it's maybe already fixed in APIM 4.0.5

**Comment by nicomanzoni** [comment] 2023-08-30 06:10
Just tried it with version 4.0 published 28th Aug, still same case of when I initially start the stack it works, and after restarting the management_ui container it gets redirected.

**Comment by nicomanzoni** [comment] 2023-09-08 05:50
To add to this issue: Once the problem arises, deleting and recreating the UI container, in addition to emptying the browser cache, solves the problem, but only until the next container restart.

**Comment by gaetanmaisse** [comment] 2023-09-11 06:39
@nicomanzoni, we might have found the root cause! We are working on a fix right now, I will keep you posted

**Closed** 2023-09-11 12:23 UTC
Labels: type: bug, project: APIM
