### ISSUE TITLE
[expression language] spaces are not well managed

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#6466] opened 2021-10-28 08:44 UTC
Since #5938 (gio-expression-language v 1.5.1), some valid expressions in 1.5.0 are not working anymore that may lead to error when HTTP Identity Provider is used on AM.

Example of payload to evaluate by the template engine:

`{ "username": "{#principal}", "password":  "{#credentials}"}`

Error generated by the gio-el module:

```
org.springframework.expression.spel.SpelParseException: EL1041E: After parsing a valid expression, there is still more data in the expression: 'colon(:)'
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.doParseExpression(InternalSpelExpressionParser.java:135)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:61)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:33)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpressions(TemplateAwareExpressionParser.java:121)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseTemplate(TemplateAwareExpressionParser.java:62)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpression(TemplateAwareExpressionParser.java:49)
	at io.gravitee.el.spel.SpelTemplateEngine.parseExpression(SpelTemplateEngine.java:52)
	at io.gravitee.el.spel.SpelTemplateEngine.getValue(SpelTemplateEngine.java:67)
	at io.gravitee.am.identityprovider.http.authentication.HttpAuthenticationProvider.processRequest(HttpAuthenticationProvider.java:205)
	at io.gravitee.am.identityprovider.http.authentication.HttpAuthenticationProvider.loadUserByUsername(HttpAuthenticationProvider.java:99)
```

### Expected Behavior

The payload is processed without error

### Current Behavior

An error is raised and the user authentication fails on AM

### Your Environment
* Version used: expression language 1.5.1

**Comment by tcompiegne** [comment] 2021-11-05 11:04
Duplicate of https://github.com/gravitee-io/issues/issues/6438

**Closed by tcompiegne** 2021-11-05 11:04 UTC
Labels: type: bug, project: AM, project: platform, Reg
