### ISSUE TITLE
[Management] [UI] Error page on Factor details if plugin isn't deployed 

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7880] opened 2022-06-23 07:20 UTC
If I have a MFA factor configured and if AM start without the related MFA plugin, we can't access to the factor page in order to delete it.

### Expected Behavior

The factor detail page should be display in order to be able to delete the factor.

### Current Behavior

A 404 Error page is displayed

### Steps to Reproduce (for bugs)
1. Start AM and configure a factor
2. Stop AM
3. Remove the plugin linked to the factor from the Management API installation
4. Start AM
5. Go to the factor description page
6. You land on 404 Error page

**Comment by tcompiegne** [comment] 2022-06-23 12:15
Duplicate of #7881

**Closed by tcompiegne** 2022-06-23 12:15 UTC
Labels: project: AM, type: uat
