### ISSUE TITLE
[portal] Typo on subscription

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3609] opened 2020-04-18 06:13 UTC
`1 subscription`

<img width="513" alt="Capture d’écran 2020-04-18 à 08 12 51" src="https://user-images.githubusercontent.com/133094/79629772-6af28e00-814c-11ea-991a-5197d9092c51.png">

**Comment by aelamrani** [comment] 2020-04-20 09:21
Duplicate of https://github.com/gravitee-io/issues/issues/3491

**Closed by aelamrani** 2020-04-20 09:21 UTC
Labels: project: APIM, type: uat
