### ISSUE TITLE
[portal] [documentation] Add media upload

### ISSUE THREAD

**Issue by GGui** [gravitee-io/issues#1427] opened 2018-08-16 12:35 UTC

**Comment by brasseld** [comment] 2018-10-16 20:48
Duplicate of https://github.com/gravitee-io/issues/issues/1427

**Closed by brasseld** 2018-10-16 20:48 UTC

**Comment by GGui** [comment] 2018-10-20 09:43
Why did you close it? It's not duplicate?

**Comment by brasseld** [comment] 2018-10-20 11:07
Sorry, I copy / paste the bad link.

Here is the good one: https://github.com/gravitee-io/issues/issues/1159
