### ISSUE TITLE
[policy] Unable to get UserInfo for multiple client_id

### ISSUE THREAD

**Issue by vdbxavier** [gravitee-io/issues#1975] opened 2019-02-25 15:17 UTC
### Expected Behavior

1 API,
2 JWT Plan (1 Key for public plan and 1 other key for private plan),
2 UserInfo Policy (1 for each plan)

we want to extract user info claims for multiple client_id from multiple domains

### Current Behavior

An error occurs in policy[policy-openid-userinfo] error[io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
…
Caused by: java.lang.IllegalArgumentException: Required type parameter does not match the resource type at io.gravitee.gateway.resource.internal.ResourceManagerImpl.getResource(ResourceManagerImpl.java:173) at io.gravitee.policy.openid.userinfo.UserInfoPolicy.onRequest(UserInfoPolicy.java:59) ... 85 more ]

### Possible Solution

fix classloader to get Ressource from multiple type of Ressource ?
check JWT client_id claim to request UserInfo only if match

### Steps to Reproduce (for bugs)

1. create a ressource
2. create a policy
3. check OK
4. create a new ressource
5. check FAIL

### Your Environment

* Version used: 1.21.2
* Operating System and version: docker image demo officiel

**Comment by brasseld** [comment] 2019-02-25 15:21
Duplicate of https://github.com/gravitee-io/issues/issues/962

**Closed by brasseld** 2019-02-25 15:21 UTC
