### ISSUE TITLE
[portal] Strange API settings behaviour

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#662] opened 2017-06-26 17:45 UTC
### Context
I was creating a new API from scratch.
I skipped plan creation and deployed without starting the API.

I went to the policies, and i've added a Dynamic Routing policy on which i have done several tests (deployed many times until having a correct answer)

After a while, my dynamic routing policy content was : {#endpoints['PIC']}{#goup[0]} 

At this step, the policy was working well, but on my API calls, i got some errors because the endpoints was in https without a trusted certificate.

So we went to the endpoints settings to enable Client SSL & Trust all option.

### Unexpected behaviour
After a save & deploy, we make a new test, and this time we got a dynamic routing policy error, we check the policy and we saw that for an unknown reason, the policy settings have been rollbacked to a previous (wrong) value :

![capture d ecran 2017-06-26 a 19 39 59](https://user-images.githubusercontent.com/16895682/27552339-51976008-5aa7-11e7-8102-bbda15403d39.png)

![capture d ecran 2017-06-26 a 19 40 13](https://user-images.githubusercontent.com/16895682/27552355-594cb708-5aa7-11e7-86ed-7a9929b4cc13.png)

Could you investigate
* Version used: 1.6
* Browser Name and version: Chrome Version 58.0.3029.110 (64-bit)
* Operating System and version: Mac OS Sierra 10.12.5

**Comment by aelamrani** [comment] 2017-09-15 13:14
Duplicate of #618

**Closed by aelamrani** 2017-09-15 13:14 UTC
Labels: type: bug
