### ISSUE TITLE
[portal] Blank home page and error when no public API

### ISSUE THREAD

**Issue by lauthieb** [gravitee-io/issues#697] opened 2017-07-19 10:06 UTC
When we don't have any public API, we have a 500 error on /management/apis and the home page is blank

### Current Behavior

<img width="1349" alt="capture d ecran 2017-07-19 a 12 00 08" src="https://user-images.githubusercontent.com/9600228/28361883-9aa181fe-6c7a-11e7-8d3e-b6b81a5d92a7.png">

<img width="473" alt="capture d ecran 2017-07-19 a 12 04 39" src="https://user-images.githubusercontent.com/9600228/28361853-75b5046a-6c7a-11e7-989d-301aff2d8b62.png">

### Steps to Reproduce (for bugs)

1. Go to Gravitee with no user connected
2. See the problem on the home page

### Your Environment

* Version used: 1.8.1
* Browser Name and version: Chrome
* Operating System and version: Mac OS

**Comment by aelamrani** [comment] 2017-07-19 10:27
Duplicate of #696

**Closed by aelamrani** 2017-07-19 10:27 UTC
