### ISSUE TITLE
[question] How to route to one of multiple endpoints ?

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#435] opened 2017-02-08 10:38 UTC
I made a dynamic routing with this expression:
redirect to:
{#endpoints['output' ]}{#group[0]}

It works well if my endpoint call output. But i have to create several endpoints output. And i have to put unique name (no error on this) : so i create output_1 and output_2.
But now routing fail.

How to write this routing: {#endpoints['output' *]}{#group[0]}  ?

thanks for you help

### Your Environment
* Version used: 1.2.0

**Comment by brasseld** [comment] 2017-02-08 10:45
Hi @vdelattre,

I'm sorry but I don't understand what you mean.
I understand that you want to call an endpoint using dynamic routing, but I don't understand the nature of `{#endpoints['output' *]}{#group[0]}`.

I've probably missed something ?

**Comment by vdelattre** [comment] 2017-02-08 10:49
I want to call an endpoint using dynamic routing. But i have several endpoints, by example output_1, output_2.
How to write routing function to call one of endpoints and have benefit of load balancing ?

i hope it's more understandable

**Comment by brasseld** [comment] 2017-02-08 13:17
ok I see.

I think you do not want to invoke a single endpoint but a group of endpoints and apply load-balancing on it, right ?

**Comment by vdelattre** [comment] 2017-02-08 13:28
yes it's right

**Comment by vdelattre** [comment] 2018-01-19 15:30
Did you work on this point?

**Comment by aelamrani** [comment] 2018-01-19 17:43
As a workaround you can apply something like: `{#endpoints["output" + ((T(java.lang.Math).random() * 2)+1).intValue()]}` to simulate a random LB behavior

**Comment by brasseld** [comment] 2018-04-26 12:52
Duplicate of https://github.com/gravitee-io/issues/issues/435

**Closed by brasseld** 2018-04-26 12:52 UTC
Labels: type: question
