### ISSUE TITLE
[APIM|GATEWAY] Node_health probe memory and cpu does not work correctly

### ISSUE THREAD

**Issue by DanilEvt** [gravitee-io/issues#7847] opened 2022-06-17 08:57 UTC
## :collision: Describe the bug
Gravity was updated from version 3.15.3->3.17.3.
We had an alert set up for node_health metrics
I know that after the update, node_health has been changed
 - Before (**3.15.3**): 0 -> everything is ok
 - Now (**3.17.3**): 1 -> everything is ok

We have changed the alert:
 - Before( **3.15.3**): `node_health != 0`
 - Now (**3.17.3**): `node_health == 0`

The jump on the chart is the moment of the update. After the update, alerts began to come only for probe memory and cpu.
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/100578907/174258711-770b8b52-0fd5-4632-af12-e5f821bf6261.png">
But this does not reflect the real situation, memory is not used by 80%, we have not changed the default setting.
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/100578907/174258972-a7ea474a-d576-4fea-8812-7dda3b15cc26.png">

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Set gravitee_services_metrics_enabled=true, gravitee_services_metrics_prometheus_enabled=true
2. Add a target to prometheus
3. Wait for a while and execute the request in prometheus node_health{probe=~"memory|cpu"}

## :rainbow: Expected behaviour
Node health probe=memory|cpu, if memory is not used more than the threshold value, the metric should be 1

## Current behaviour
Node_health probe=memory|cpu does not display the real situation

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [3.17.3]
 - OS: [CentOS 7]
 - Browser [chrome]

**Comment by gaetanmaisse** [comment] 2022-08-11 07:46
@DanilEvt thanks for the issue!

After investigation, it looks like the behavior you had in `3.15.3` wasn't the correct one and was related to the upgrade to VertX we did in a previous version. Some details can be found at https://github.com/gravitee-io/issues/issues/6924.

The PR which fixes this is https://github.com/gravitee-io/gravitee-node/pull/119, it was first released in `3.10.11`, then landed in `3.15.4` and the upper version. 

The behavior you're seeing now is the expected behavior (and the same as in the older APIM versions). 

If you think I'm missing something please reopen the issue and tag me :)

**Closed by gaetanmaisse** 2022-08-11 07:46 UTC
Labels: type: bug, project: APIM, p2
