### ISSUE TITLE
[plugin] Unused open file pointers left by URLClassLoader

### ISSUE THREAD

**Issue by k-oliver** [gravitee-io/issues#2920] opened 2019-11-21 16:00 UTC
When loading plugins from .work directory using URLClassLoader some file pointers are left open because the URLClassLoader is not closed.

### Expected Behavior
Close no more used ClassLoaders.

### Current Behavior
ClassLoader left open.

### Possible Solution
I will provide a PR...

### Steps to Reproduce (for bugs)
Start gravitee and take a look at the open files.

**Comment by brasseld** [comment] 2019-11-21 16:01
Hi @k-oliver 

That's interesting.

Which version of G.IO are you using?

**Comment by k-oliver** [comment] 2019-11-21 16:03
I'm on 1.29.5.

**Comment by brasseld** [comment] 2019-11-21 16:06
Can you tell me which useless classloader are not closed ? For which kind of plugin ?

**Comment by k-oliver** [comment] 2019-11-21 16:09
I can see changes in the latest version at this point. It was the handle(Plugin plugin) method in for example /gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java.
May be you already fixed this. I will have a close look to the latest version.

**Comment by brasseld** [comment] 2019-11-21 16:11
So yes, it has been fixed indirectly in 1.30 with some plugin enhancement.

The issue is still relevant for versions between 1.25 and 1.29

**Comment by k-oliver** [comment] 2019-11-21 16:15
Great, i will update to 1.30. It's easy to fix by just closing the URLClassLoader at /gravitee-plugin-fetcher/src/main/java/io/gravitee/plugin/fetcher/internal/FetcherPluginHandler.java and /gravitee-plugin-service-discovery/src/main/java/io/gravitee/plugin/discovery/internal/ServiceDiscoveryPluginHandler.java. So i guess you don't need a PR?

**Comment by brasseld** [comment] 2019-11-21 16:38
I believe you're better than me with classloaders :)
PR is still relevant if it's not annoying you.
Thanks a lot

**Comment by k-oliver** [comment] 2019-11-21 16:53
Is 1.9.x the right branch?

**Comment by brasseld** [comment] 2019-11-21 17:01
that's ok. if not I will cherry-pick your commit, no worries.

**Closed** 2019-12-04 15:45 UTC
Labels: project: platform, type: bug
