### ISSUE TITLE
[gateway] Allow EL int the backend "target" field

### ISSUE THREAD

**Issue by David-V2** [gravitee-io/issues#907] opened 2017-11-24 08:59 UTC
### Context
I would like to automate the propagation of my API between environments.
To be able to do this, I need to simplify the API configuration by removing any "by environment" specificity.

### Current Behavior
So I tried to set my target field with this : 
{#properties["first_endpoint"]} but the form validation do not allow it

I tried : https://{#properties["first_endpoint"]}/
And I was able to save and publish the API, but the gateway log an error
``` 
java.lang.IllegalArgumentException: Illegal character in authority at index 8: https://{#properties["first_endpoint"]}/
```

### Expected Behavior
I would like to be able to use SpEL in this field with values like {#properties["first_endpoint"]} 

### Steps to Reproduce (for bugs)
1. Set a properties
2. Try to use the property in the backend target field

**Comment by David-V2** [comment] 2018-05-16 12:11
I'd like to push up this enhancement.

Today we have updated the APIM on the production platform, from 1.12.5 to 1.14.4.
An API have stopped working because of a misconfigurated API (a tenant set on the backend of a non-multi-tenant API). But the bad configuration didn't have consequences in 1.12 ...

Since the configuration is a manual process, the error wasn't on the UAT environment ...

This feature will help me script a propagation bot to remove any needs of handmade actions !
(this script is doable today, but the code would be a real mess ...)

**Comment by tcompiegne** [comment] 2018-07-19 16:14
See #1401

**Comment by brasseld** [comment] 2018-08-14 06:51
Duplicate of https://github.com/gravitee-io/issues/issues/1401

**Closed by brasseld** 2018-08-14 06:51 UTC
Labels: type: enhancement
