### ISSUE TITLE
[portal] subscribe to an api from the api list

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#135] opened 2016-07-07 22:24 UTC
A user must be able to subscribe to an api (ie, get an api-key) from the api list.

If I choose to subscribe to an api and if I have only one application, the apikey must be associated to this application and we must display the api-key.
If I choose to subscribe to an api and if I have several applications, Gravitee.io will display my applications list and I have to choose the application.

**Comment by brasseld** [comment] 2016-07-07 22:32
How should it work when 'Plans' will be added ?

**Comment by NicolasGeraud** [comment] 2016-07-07 22:40
As a API Publisher of a public API, I have to set a default plan.
Or
Plan will be show on the api (some could be disabled) and the subscriber choose which plan match better its needs.

I think the second solution is better. And when social part will be implement in Gravitee.io, the subscriber could request for an api-key to a specific plan.

**Comment by brasseld** [comment] 2016-07-07 22:45
We have to think about the scenario.

I think that, we a user ask for an API Key, he must be redirected to a Plans page for the selected API.
Then he selects the plan which fit its need and associate it to one of his applications (or create a new one).

**Comment by NicolasGeraud** [comment] 2016-07-07 22:49
so you're agree with me 😄

**Comment by lusoalex** [comment] 2016-08-01 09:59
Hello, 

I guess we will have plans like "freemium, silver, golden..."
Do you expect to give possibility  to create customs plans for a dedicated API (or a group of API)?

I do not find the issue to manage plan, is it already created?

Regards,
Alexandre.

**Comment by brasseld** [comment] 2016-10-16 16:48
Duplicate of gravitee-io/issues#257

**Closed by brasseld** 2016-10-16 16:48 UTC
Labels: type: duplicate, type: feature
