### ISSUE TITLE
APIM Gateway  Queue is full

### ISSUE THREAD

**Issue by yazalulloa** [gravitee-io/issues#6082] opened 2021-09-02 13:44 UTC
I'm having this logs show up in the gateway log, I'm running version 3.9.1 on docker, sometimes the gateway does not log the requests, sometimes it does.

02:31:53.178 [gio-heartbeat] [] ERROR i.g.g.s.heartbeat.HeartbeatThread - An unexpected error occurs while monitoring the gateway
java.lang.IllegalStateException: Queue is full!
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.add(QueueProxyImpl.java:59)
	at io.gravitee.gateway.services.heartbeat.HeartbeatThread.run(HeartbeatThread.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
02:31:58.179 [gio-heartbeat] [] ERROR i.g.g.s.heartbeat.HeartbeatThread - An unexpected error occurs while monitoring the gateway
java.lang.IllegalStateException: Queue is full!
	at com.hazelcast.collection.impl.queue.QueueProxyImpl.add(QueueProxyImpl.java:59)
	at io.gravitee.gateway.services.heartbeat.HeartbeatThread.run(HeartbeatThread.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

This log shows up every couple of seconds without any other information

**Comment by brasseld** [comment] 2021-09-02 15:27
Something to check, but I'm pretty sure it's been fixed from latest 3.9.x versions.

**Comment by yazalulloa** [comment] 2021-09-02 16:05
I'll update it to the newest version and will check

**Comment by yazalulloa** [comment] 2021-09-02 16:19
I upgrade it to 3.10.0 and now it show this:

16:18:29.988 [vert.x-eventloop-thread-6] [] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NoClassDefFoundError: org/LatencyUtils/PauseDetector
        at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:199)
        at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:310)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:614)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:568)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:308)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:400)
        at io.vertx.micrometer.impl.meters.Timers.get(Timers.java:50)
        at io.vertx.micrometer.impl.meters.Timers$EventTiming.end(Timers.java:67)
        at io.vertx.micrometer.impl.VertxHttpClientMetrics$Instance$1.dequeueRequest(VertxHttpClientMetrics.java:86)
        at io.vertx.micrometer.impl.VertxHttpClientMetrics$Instance$1.dequeueRequest(VertxHttpClientMetrics.java:76)
        at io.vertx.core.http.impl.ClientHttpEndpointBase.lambda$requestConnection$0(ClientHttpEndpointBase.java:44)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:161)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:122)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:49)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:275)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.emit(SimpleConnectionPool.java:624)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectSuccess.lambda$execute$1(SimpleConnectionPool.java:316)
        at io.vertx.core.net.impl.pool.CombinerExecutor.pollAndExecute(CombinerExecutor.java:55)
        at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:43)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:231)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.lambda$connect$2(SimpleConnectionPool.java:243)
        at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.lambda$connect$2(SharedClientHttpStreamEndpoint.java:101)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
        at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.Promise.complete(Promise.java:66)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connected$6(NetClientImpl.java:261)
        at io.vertx.core.net.impl.VertxHandler.setConnection(VertxHandler.java:83)
        at io.vertx.core.net.impl.VertxHandler.handlerAdded(VertxHandler.java:89)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
        at io.vertx.core.net.impl.NetClientImpl.connected(NetClientImpl.java:263)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$1(NetClientImpl.java:228)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
        at io.vertx.core.net.impl.ChannelProvider.connected(ChannelProvider.java:174)
        at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$0(ChannelProvider.java:157)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:653)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:691)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by brasseld** [comment] 2021-09-14 18:24
Duplicate of https://github.com/gravitee-io/issues/issues/5996

**Closed by brasseld** 2021-09-14 18:24 UTC
Labels: type: duplicate, project: APIM
