### ISSUE TITLE
Reason for the rejection in case of error 401

### ISSUE THREAD

**Issue by Produits** [gravitee-io/issues#2341] opened 2019-06-07 08:07 UTC
Hi,

When a flow is rejected due to an authentication problem (error 401), we do not have log information on the HMI about the reason for the rejection.
Would it be possible to have the consumer part with the characteristics of the incoming flow and the returned response?
This would facilitate analysis in the event of a problem.

Thank you.

**Comment by brasseld** [comment] 2020-06-01 21:14
Duplicate of https://github.com/gravitee-io/issues/issues/3891

Part of 1.30.12

**Closed by brasseld** 2020-06-01 21:14 UTC
