### ISSUE TITLE
404 Error - Gravitee AM Web UI login

### ISSUE THREAD

**Issue by gianx89** [gravitee-io/issues#3829] opened 2020-05-21 15:41 UTC
I've just updated and migrated my gravitee AM instance to the latest V3.
I'm running it on docker using your docker composer file.

When I browse to "am/ui" I've being redirected to http://172.31.33.211/am/management/auth/authorizeredirect_uri=http://172.31.33.211/login/callback

then to

http://172.31.33.211/management/auth/login

It seems that the url is missing the "am" part or that nginx is not working properly. Never had this problem before.

Same problem on a fresh installation, can't login to web ui

What should I do?

**Comment by tcompiegne** [comment] 2020-05-21 16:28
Duplicate of #3827

**Closed by tcompiegne** 2020-05-21 16:28 UTC
