### ISSUE TITLE
Traffic Shadowing Policy only returns "NoSuchMethodError: 'io.gravitee.gateway.api.proxy.ProxyConnection"

### ISSUE THREAD

**Issue by JonathanBennett** [gravitee-io/issues#6025] opened 2021-08-22 13:13 UTC
### Expected Behavior

When configuring the Traffic Shadowing policy with either an EL endpoint or a direct target (https://...) the traffic shadowing policy should send a request to the shadow service.

### Current Behavior

When configuring the URL either via Endpoint/Endpoint Groups or direct target link, all result in the following stacktrace and the shadow service never receives the request. The API completes as normal. 

Stacktrace: 

```java
13:03:56.291 [vert.x-eventloop-thread-0] [] ERROR i.g.g.policy.impl.OrderedPolicyChain - Unexpected error while running onXXXXContent for policy io.gravitee.gateway.policy.impl.ExecutablePolicy@44cb7b7c
io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.invoke(ExecutablePolicy.java:84)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.stream(ExecutablePolicy.java:55)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.prepareStreamablePolicyChain(StreamablePolicyChain.java:62)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:49)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:72)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:34)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:80)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.policy.keyless.KeylessPolicy.onRequest(KeylessPolicy.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.invoke(ExecutablePolicy.java:82)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.execute(ExecutablePolicy.java:50)
	at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:67)
	at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:53)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:96)
	at io.gravitee.gateway.policy.impl.PolicyChain.handle(PolicyChain.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.handlers.api.processor.cors.CorsPreflightRequestProcessor.handle(CorsPreflightRequestProcessor.java:53)
	at io.gravitee.gateway.handlers.api.processor.cors.CorsPreflightRequestProcessor.handle(CorsPreflightRequestProcessor.java:33)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:72)
	at io.gravitee.gateway.core.logging.processor.LoggableRequestProcessor.handle(LoggableRequestProcessor.java:34)
	at io.gravitee.gateway.core.processor.StreamableProcessorDecorator.handle(StreamableProcessorDecorator.java:38)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.lambda$handle$1(AbstractStreamableProcessorChain.java:58)
	at io.gravitee.gateway.core.processor.EmptyStreamableProcessor.handle(EmptyStreamableProcessor.java:30)
	at io.gravitee.gateway.core.processor.chain.AbstractStreamableProcessorChain.handle(AbstractStreamableProcessorChain.java:62)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:110)
	at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:86)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:91)
	at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:42)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$3(DefaultReactor.java:101)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:43)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.transaction.TransactionProcessor.handle(TransactionProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.lambda$handle$0(AbstractProcessorChain.java:38)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:60)
	at io.gravitee.gateway.reactor.processor.forward.XForwardForProcessor.handle(XForwardForProcessor.java:29)
	at io.gravitee.gateway.core.processor.chain.AbstractProcessorChain.handle(AbstractProcessorChain.java:41)
	at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:109)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.route(VertxReactorHandler.java:63)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:59)
	at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:35)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:49)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:167)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.gravitee.gateway.policy.impl.ExecutablePolicy.invoke(ExecutablePolicy.java:82)
	... 94 common frames omitted
Caused by: java.lang.NoSuchMethodError: 'io.gravitee.gateway.api.proxy.ProxyConnection io.gravitee.gateway.api.Connector.request(io.gravitee.gateway.api.proxy.ProxyRequest)'
	at io.gravitee.policy.trafficshadowing.TrafficShadowingPolicy.onRequestContent(TrafficShadowingPolicy.java:60)
	... 99 common frames omitted
```

### Possible Solution

The method required from the ProxyConnection class appears to be unavailable.

### Steps to Reproduce (for bugs)

1. Create a new API + complete the steps.
2. Define an Endpoint group with a target endpoint
3. Configure the traffic shadowing policy with the target
4. Issue a request, and observe the logs

### Context

We are trying to mirror all our traffic to another service to assist with migration. We could do an HTTP Callout, but the "fire and forget" setting has only appeared in the latest version of the plugin which would make it's behaviour match that of the traffic shadowing policy.

### Your Environment

* Version used: 3.10.0
* Browser Name and version: N/A
* Operating System and version: Gravitee 3.10.0 Docker Images on Google Container OS.

**Comment by ppgravitee** [comment] 2022-12-02 09:02
duplicate of #8385

**Closed by ppgravitee** 2022-12-02 09:02 UTC
Labels: type: bug, status: on hold, project: APIM, p2, need-archi, wontfix
