### ISSUE TITLE
Json Validation Policy does not work with callout-http policy. Json Validation Policy is not returning error message. Normally I call the API with a non-valid json, but the callout-http policy still works.

### ISSUE THREAD

**Issue by aliFetvaci61** [gravitee-io/issues#7088] opened 2022-02-10 11:51 UTC
Json Validation Policy does not work with callout-http policy. Json Validation Policy is not returning error message. Normally I call the API with a non-valid json, but the callout-http policy still works. I disable callout-http policy and Json validation policy works and returns error. I don't understand why this is happening?

APIM version 3.6.0

!<span class="error">[image]</span>([https://user-images.githubusercontent.com/16122994/153402985-5fd8b6c1-247e-48fb-9125-5067aefa972c.png](https://user-images.githubusercontent.com/16122994/153402985-5fd8b6c1-247e-48fb-9125-5067aefa972c.png))

**Comment by gaetanmaisse** [comment] 2023-07-12 11:59
I am closing the issue as I couldn't reproduce the issue, at least with APIM 3.19+. Feel free to reopen it and provide the export of an API reproducing the problem.

**Closed by gaetanmaisse** 2023-07-12 11:59 UTC
Labels: type: bug, project: APIM
