### ISSUE TITLE
[portal] menu items sizes are reduced when we scroll down

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#5155] opened 2021-03-01 23:22 UTC
### Steps to Reproduce (for bugs)

1. go to the portal, scroll down

<img width="770" alt="Capture d’écran 2021-03-02 à 00 19 38" src="https://user-images.githubusercontent.com/1028285/109572343-56fa1580-7aed-11eb-9743-c89b12455500.png">

### Your Environment

* Version used: 3.5.5

**Comment by aelamrani** [comment] 2021-03-16 05:10
Duplicate of https://github.com/gravitee-io/issues/issues/5233

**Closed by aelamrani** 2021-03-16 05:10 UTC
Labels: Support, project: APIM, type: bug
