### ISSUE TITLE
[Task] Cypress tests for [management] [mfa] HTTP factor

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7426] opened 2022-04-01 09:58 UTC
### 💼 Parent Issue

https://github.com/gravitee-io/issues/issues/7374

### 📝 Description

Cypress tests for [management] [mfa] HTTP factor

**Comment by tcompiegne** [comment] 2022-04-14 13:20
Duplicate of #7425

**Closed by tcompiegne** 2022-04-14 13:20 UTC
Labels: type: technical, project: AM
