### ISSUE TITLE
Gravitee with JDBC(mysql) instead of MongoDB

### ISSUE THREAD

**Issue by sunilb20** [gravitee-io/issues#1306] opened 2018-06-13 06:36 UTC
As per the documentation, Gravitee-repository-jdbc should be part of plugins, but its not. However I see gravitee-repository-mongodb under plugin folder which works fine.

We want to use the mysql db in production instead of Mongodb.

Is this feature available ?

**Environment**
Version used: 1.16.3

**Comment by NicolasGeraud** [comment] 2018-06-13 06:39
hi @sunilb20 ,
yes it's available.

jdbc plugins are here : https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-jdbc/

see here to know how to configure it https://docs.gravitee.io/apim_installguide_repositories_jdbc.html

**Comment by sunilb20** [comment] 2018-06-13 06:41
Thanks for prompt response.

I built the jdbc plugin manually and put it in plugins, but gravitee startup throws the following error : 

16:08:43.120 [gravitee] [] ERROR i.g.g.s.h.NodeHealthcheckService - Unexpected error while creating an health-check probe for io.gravitee.gateway.services.healthcheck.probe.RateLimitRepositoryProbe
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.gravitee.gateway.services.healthcheck.probe.RateLimitRepositoryProbe': Unsatisfied dependency expressed through field 'rateLimitRepository'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean found for dependency [io.gravitee.repository.ratelimit.api.RateLimitRepository]: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)

**Comment by NicolasGeraud** [comment] 2018-06-13 06:44
indeed ... our documentation need updates.

in the gravitee.yml file of the gateway, you probably still have the default repository type for the ratelimit (mongodb).

see https://github.com/gravitee-io/gravitee-gateway/blob/f45a23b834d4ea1779d5c64685913802d44504b0/gravitee-gateway-standalone/gravitee-gateway-standalone-distribution/src/main/resources/config/gravitee.yml#L96

**Comment by sunilb20** [comment] 2018-06-13 06:49
I had changed gravitee.yml as given below :
1. 
management:
  type: jdbc
  jdbc:
    url: jdbc:mysql://${ds.jdbc.host}:${ds.jdbc.port}/${ds.jdbc.dbname}

2. 
ratelimit:
  type: jdbc
  jdbc:
    url: jdbc:mysql://${ds.jdbc.host}:${ds.jdbc.port}/${ds.jdbc.dbname}

3. 

ds:
  mongodb:
    dbname: gravitee
    host: ${GRAVITEEIO_MONGODB_HOST:localhost}
    port: ${GRAVITEEIO_MONGODB_PORT:27017}
  elastic:
    host: ${GRAVITEEIO_ELASTIC_HOST:localhost}
    port: ${GRAVITEEIO_ELASTIC_PORT:9200}
  jdbc:
    dbname: gravitee
    host: ${GRAVITEEIO_JDBC_HOST:100.130.135.112}
    port: ${GRAVITEEIO_JDBC_PORT:3600}

**Comment by NicolasGeraud** [comment] 2018-06-13 06:51
please provide the full gravitee.log on startup

**Comment by sunilb20** [comment] 2018-06-13 06:54
[gravitee.log](https://github.com/gravitee-io/issues/files/2096919/gravitee.log)

**Comment by NicolasGeraud** [comment] 2018-06-13 06:56
```java.nio.file.AccessDeniedException: E:\Softwares\gateways\gravitee\graviteeio-full-1.16.3\graviteeio-gateway-1.16.3\plugins\gravitee-repository-jdbc-1.17.0-SNAPSHOT.zip```

**Comment by sunilb20** [comment] 2018-06-13 07:35
Thanks for pointing that out. 
After resolving that issue, I am getting following : 

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'gravitee.apis' doesn't exist
        at sun.reflect.GeneratedConstructorAccessor110.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
        at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
        at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
        at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:458)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
        ... 16 common frames omitted
13:02:30.513 [refresher-1] ERROR i.g.r.j.management.JdbcApiRepository - Failed to find all users:
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select * from apis a left join api_views av on a.id = av.api_id]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'gravitee.apis' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)

**Comment by sunilb20** [comment] 2018-06-13 07:35
Is the table created manually ?

**Comment by NicolasGeraud** [comment] 2018-06-13 07:37
No, we use liquibase.

You just need to create the schema (gravitee by default)

**Comment by sunilb20** [comment] 2018-06-13 07:39
But as pointed above the server startup fails for apis table.

**Comment by NicolasGeraud** [comment] 2018-06-13 07:41
you probably have liquibase errors on startup

**Comment by aelamrani** [comment] 2018-06-13 07:41
Is your database <code>gravitee</code> created?

**Comment by sunilb20** [comment] 2018-06-13 07:47
I am using distributable zip 'graviteeio-full-1.16.3.zip' and not building the projects.

How do I resolve it?

**Comment by sunilb20** [comment] 2018-06-13 07:48
@aelamrani , Yes Its created.

**Comment by NicolasGeraud** [comment] 2018-06-13 07:48
and no table are created ?

**Comment by aelamrani** [comment] 2018-06-13 07:49
please provide the complete log?

**Comment by sunilb20** [comment] 2018-06-13 07:49
It shows following tables created
![image](https://user-images.githubusercontent.com/24645049/41337288-72e9d4be-6f0c-11e8-885f-b965bb1742b2.png)

**Comment by aelamrani** [comment] 2018-06-13 07:52
could you please drop all the tables and start again?

**Comment by sunilb20** [comment] 2018-06-13 07:57
Tried that and attached is the full log

**Comment by aelamrani** [comment] 2018-06-13 07:58
cannot find the attachment... also which version of mysql you use?

**Comment by sunilb20** [comment] 2018-06-13 07:58
[gravitee.txt](https://github.com/gravitee-io/issues/files/2097164/gravitee.txt)

**Comment by aelamrani** [comment] 2018-06-13 08:06
Did you check the log by yourself?

There is stacktrace like this: 

> 13:25:16.313 [gravitee] [] WARN  c.zaxxer.hikari.pool.ProxyConnection - gravitee-jdbc-pool-1 - Connection com.mysql.jdbc.JDBC4Connection@14faa38c marked as broken because of SQLSTATE(08S01), ErrorCode(0)
> com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
> 
> The last packet successfully received from the server was 19,693 milliseconds ago.  The last packet sent successfully to the server was 19,693 milliseconds ago.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
> 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
> 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
> 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3903)
> 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
> 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
> 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
> 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
> 	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
> 	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
> 	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
> 	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
> 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
> 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
> 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
> 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
> 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
> 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
> 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
> 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
> 	at liquibase.Liquibase.update(Liquibase.java:214)
> 	at liquibase.Liquibase.update(Liquibase.java:192)
> 	at liquibase.Liquibase.update(Liquibase.java:188)
> 	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.runLiquibase(AbstractJdbcRepositoryConfiguration.java:130)
> 	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.graviteeDataSource(AbstractJdbcRepositoryConfiguration.java:104)
> 	at io.gravitee.repository.jdbc.common.AbstractJdbcRepositoryConfiguration.setApplicationContext(AbstractJdbcRepositoryConfiguration.java:78)
> 	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
> 	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
> 	at io.gravitee.plugin.core.internal.PluginContextFactoryImpl.create(PluginContextFactoryImpl.java:59)
> 	at io.gravitee.gateway.repository.plugins.RepositoryPluginHandler.handle(RepositoryPluginHandler.java:97)
> 	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$null$2(PluginEventListener.java:108)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at io.gravitee.plugin.core.internal.PluginEventListener.lambda$deployPlugins$3(PluginEventListener.java:106)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:103)
> 	at io.gravitee.plugin.core.internal.PluginEventListener.deployPlugins(PluginEventListener.java:88)
> 	at io.gravitee.plugin.core.internal.PluginEventListener.onEvent(PluginEventListener.java:63)
> 	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:44)
> 	at io.gravitee.common.event.impl.EventManagerImpl.publishEvent(EventManagerImpl.java:36)
> 	at io.gravitee.plugin.core.internal.PluginRegistryImpl.init(PluginRegistryImpl.java:105)
> 	at io.gravitee.plugin.core.internal.PluginRegistryImpl.doStart(PluginRegistryImpl.java:81)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.common.node.AbstractNode.doStart(AbstractNode.java:53)
> 	at io.gravitee.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:32)
> 	at io.gravitee.gateway.standalone.Container.start(Container.java:108)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at io.gravitee.gateway.standalone.boostrap.Bootstrap.start(Bootstrap.java:162)
> 	at io.gravitee.gateway.standalone.boostrap.Bootstrap.main(Bootstrap.java:171)
> Caused by: java.net.SocketTimeoutException: Read timed out
> 	at java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:170)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
> 	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
> 	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
> 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
> 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)
> 	... 77 common frames omitted

**Comment by aelamrani** [comment] 2018-06-13 09:07
@sunilb20 is this OK now? Can i close this issue?

**Comment by sunilb20** [comment] 2018-06-13 09:16
Hi,
I see that same database is being connected and tables being created. Why its loosing connection after that. I see the below logs before the logs you mentioned - 

13:24:52.205 [gravitee] [] INFO  liquibase - **Creating database history table with name: gravitee.databasechangelog**
13:24:52.207 [gravitee] [] DEBUG liquibase - Executing EXECUTE database command: CREATE TABLE gravitee.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, DESCRIPTION VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL)
13:24:52.915 [gravitee] [] DEBUG liquibase - Executing QUERY database command: select count(*) from gravitee.databasechangelog
13:24:53.022 [gravitee-jdbc-pool-1 connection adder] [] DEBUG com.zaxxer.hikari.pool.HikariPool - gravitee-jdbc-pool-1 - Added connection com.mysql.jdbc.JDBC4Connection@33e2a999
13:24:53.101 [gravitee] [] INFO  liquibase - Reading from gravitee.databasechangelog
13:24:53.101 [gravitee] [] DEBUG liquibase - Executing QUERY database command: SELECT * FROM gravitee.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
13:24:53.452 [gravitee] [] DEBUG liquibase - Executing QUERY database command: select count(*) from gravitee.databasechangeloglock
13:24:53.813 [gravitee] [] DEBUG liquibase - liquibase/master.yml: liquibase/changelogs/v1_14_0/schema.yml::1.14.0::GraviteeSource Team: Computed

**Comment by sunilb20** [comment] 2018-06-13 09:17
I am using jdbc for both Management and RateLimit.

**Comment by aelamrani** [comment] 2018-06-13 09:18
Probably you have network issues... Are you behind a proxy?

**Comment by sunilb20** [comment] 2018-06-13 09:20
no I dont think so. Server start successfully creates 4 tables as mentioned above and then fails. I dont get why that behaviour ?

**Comment by aelamrani** [comment] 2018-06-13 09:27
I'm sorry but IMHO it's a network issue: 

> Caused by: liquibase.exception.DatabaseException: Communications link failure

and 

> Caused by: java.net.SocketTimeoutException: Read timed out

So maybe the link is broken by a component between gravitee.io and your database server... but as i have no clue about your infrastructure, i can't help on this point.

**Comment by sunilb20** [comment] 2018-06-13 09:34
Please See logs below : It says the connections was setup on server startup. I had sent the full logs as well earlier ,
Let me know if you can suggest me something
13:24:42.659 [gravitee] [] INFO  com.zaxxer.hikari.HikariDataSource - gravitee-jdbc-pool-1 - Starting...
13:24:46.376 [gravitee] [] DEBUG com.zaxxer.hikari.pool.HikariPool - gravitee-jdbc-pool-1 - Added connection com.mysql.jdbc.JDBC4Connection@14faa38c
13:24:46.442 [gravitee] [] INFO  com.zaxxer.hikari.HikariDataSource - gravitee-jdbc-pool-1 - Start completed.
13:24:46.444 [gravitee] [] DEBUG i.g.r.j.c.AbstractJdbcRepositoryConfiguration - Running Liquibase on HikariDataSource (gravitee-jdbc-pool-1)
13:24:46.543 [gravitee-jdbc-pool-1 housekeeper] [] DEBUG com.zaxxer.hikari.pool.HikariPool - gravitee-jdbc-pool-1 - Pool stats (total=1, active=1, idle=0, waiting=0)
13:24:47.186 [gravitee] [] DEBUG liquibase - **Connected to root@172.16.28.56@jdbc:mysql://10.131.135.122:3306/gravitee**
13:24:47.186 [gravitee] [] DEBUG liquibase - Setting auto commit to false from true
13:24:47.640 [gravitee] [] DEBUG liquibase - Executing QUERY database command: select count(*) from gravitee.databasechangeloglock
13:24:47.903 [gravitee] [] DEBUG liquibase - Create Database Lock Table
13:24:47.915 [gravitee] [] DEBUG liquibase - Executing EXECUTE database command: CREATE TABLE gravitee.databasechangeloglock (ID INT NOT NULL, LOCKED BIT(1) NOT NULL, LOCKGRANTED datetime NULL, LOCKEDBY VARCHAR(255) NULL, CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
13:24:48.704 [gravitee-jdbc-pool-1 connection adder] [] DEBUG com.zaxxer.hikari.pool.HikariPool - gravitee-jdbc-pool-1 - Added connection com.mysql.jdbc.JDBC4Connection@3d7721ef

**Comment by aelamrani** [comment] 2018-06-13 09:38
I know the connection was setup as some tables are created. But according to the logs the connection seems to be broken...

Are you able to try locally to confirm that?

**Comment by sunilb20** [comment] 2018-06-13 10:53
Let me try local. Will update you soon.

**Comment by sunilb20** [comment] 2018-06-13 14:28
Tried with mysql database in my local. There is no connection issue but failing for same missing tables.
Attached logs for your review : 
[gravitee.txt](https://github.com/gravitee-io/issues/files/2098559/gravitee.txt)

**Comment by NicolasGeraud** [comment] 2018-06-13 14:30
not the same issue : 
```
     Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NULL, updated_at timestamp(6) NULL, last_connection_at timestamp(6) NULL, pi' at line 1 [Failed SQL: CREATE TABLE gravitee.users (id NVARCHAR(64) NOT NULL, username NVARCHAR(64) NOT NULL, source NVARCHAR(128) NULL, source_id NVARCHAR(128) NULL, password NVARCHAR(128) NULL, email NVARCHAR(128) NULL, firstname NVARCHAR(64) NULL, lastname NVARCHAR(64) NULL, created_at timestamp(6) NULL, updated_at timestamp(6) NULL, last_connection_at timestamp(6) NULL, picture LONGTEXT CHARACTER SET utf8 NULL)]
```

**Comment by NicolasGeraud** [comment] 2018-06-13 14:31
what is your mysql version and driver version ?

**Comment by sunilb20** [comment] 2018-06-13 14:35
I have mysql 5.5 installed. Dont you support the same ?
I have not changed any scripts apart from that.

**Comment by aelamrani** [comment] 2018-06-13 15:10
I'm able to reproduce this issue on your MySql version (5.5). Are you able to upgrade? At least the last release of the version 5 (5.7)?

**Comment by sunilb20** [comment] 2018-06-14 10:30
Hi,
I have an update. I am able to deploy the platform using Mysql 5.7. Able to see all the tables created and all the components running. But there is debug failure log is being printed continuously as given below 

15:57:33.762 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [delete from event_properties where event_id = ?]
15:57:33.762 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
15:57:33.893 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - SQL update affected 3 rows
15:57:33.894 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
15:57:33.894 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing SQL batch update [insert into event_properties ( event_id, property_key, property_value ) values ( ?, ?, ? )]
15:57:33.894 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [insert into event_properties ( event_id, property_key, property_value ) values ( ?, ?, ? )]
15:57:33.894 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
15:57:33.894 [gateway-monitor] [] DEBUG o.s.jdbc.support.JdbcUtils - JDBC driver supports batch updates
15:57:34.181 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
15:57:34.181 [gateway-monitor] [] DEBUG i.g.r.j.m.JdbcEventRepository - JdbcEventRepository.findById(f770623a-a3a9-4e67-b062-3aa3a9ee67d9)
15:57:34.181 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing prepared SQL query
15:57:34.181 [gateway-monitor] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing prepared SQL statement [select * from events e left join event_properties ep on e.id = ep.event_id where e.id = ?]
15:57:34.181 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
15:57:34.183 [gateway-monitor] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
15:57:34.184 [gateway-monitor] [] DEBUG i.g.g.s.m.probe.ProcessProbe - Unexpected exception
java.lang.IllegalArgumentException: java.lang.ClassCastException@7c97be61
        at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.gravitee.gateway.services.monitoring.probe.ProcessProbe.getOpenFileDescriptorCount(ProcessProbe.java:78)
        at io.gravitee.gateway.services.monitoring.probe.ProcessProbe.processInfo(ProcessProbe.java:89)
        at io.gravitee.gateway.services.monitoring.MonitorThread.run(MonitorThread.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
15:57:34.184 [gateway-monitor] [] DEBUG i.g.g.s.m.probe.ProcessProbe - Unexpected exception
java.lang.IllegalArgumentException: java.lang.ClassCastException@63c9199e
        at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.gravitee.gateway.services.monitoring.probe.ProcessProbe.getMaxFileDescriptorCount(ProcessProbe.java:63)
        at io.gravitee.gateway.services.monitoring.probe.ProcessProbe.processInfo(ProcessProbe.java:90)
        at io.gravitee.gateway.services.monitoring.MonitorThread.run(MonitorThread.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
15:57:35.002 [sync-1] [] DEBUG i.g.g.services.sync.SyncManager - Synchronization #529 started at 2018-06-14T10:27:35.002Z
15:57:35.002 [sync-1] [] DEBUG i.g.g.services.sync.SyncManager - Refreshing gateway state...
15:57:35.002 [sync-1] [] DEBUG i.g.r.j.management.JdbcApiRepository - JdbcApiRepository.findAll()
15:57:35.002 [sync-1] [] DEBUG o.s.jdbc.core.JdbcTemplate - Executing SQL query [select * from apis a left join api_views av on a.id = av.api_id]
15:57:35.002 [sync-1] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource
15:57:35.021 [sync-1] [] DEBUG o.s.jdbc.datasource.DataSourceUtils - Returning JDBC Connection to DataSource
15:57:35.021 [sync-1] [] DEBUG i.g.g.services.sync.SyncManager - Synchronization #529 ended at 2018-06-14T10:27:35.021Z

**Comment by aelamrani** [comment] 2018-06-14 10:34
IMHO that's not important logs as the level is DEBUG.

Is there any issue on gravitee.io?

If you want you can change the log level to not be pollute with theses logs.

Can i close this issue?

**Comment by sunilb20** [comment] 2018-06-14 12:35
Yes Pls. Thanks for resolving the issue.

**Closed** 2018-06-14 12:36 UTC

**Comment by NicolasGeraud** [comment] 2018-06-28 07:31
hi @tanalop ,

The documentation is here : https://docs.gravitee.io/apim_installguide_repositories_jdbc.html

The jdbc plugin is here : https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-jdbc/

Tell us if something goes wrong.

**Comment by tanalop** [comment] 2018-06-28 07:41
How to use MySQL Database instad on MongoDB .
Is this feature available ?

**Comment by aelamrani** [comment] 2018-06-28 07:43
Hi @tanalop 

Please open a new issue, as this one has been resolved

**Comment by NicolasGeraud** [comment] 2018-06-28 07:43
The documentation is not enough to answer this question ?
What is missing ?

**Comment by StodaraHodan** [comment] 2020-02-28 12:34
to be honest the documentation leaves a lot to be desired, not just in the database configuration but throughout.
For example i couldn't find how and when database objects are created, what permissions are necessary, what prerequisites are necessary if you want to use a mssql db for example. do i create an empty database? does the script create one?

**Comment by aelamrani** [comment] 2020-02-28 12:41
@StodaraHodan Yes we know that we have to improve the documentation, and any pull requests are really appreciated!

You just need to create an new empty DB yes, and everything else is handled by the plugin JDBC => schema creation, constraints... etc

**Comment by py-wy** [comment] 2020-03-26 13:16
Hello, sorry to bump on a closed issue but the jdbc documentation page returns a 404 https://docs.gravitee.io/apim_installguide_repositories_jdbc.html

**Comment by brasseld** [comment] 2020-03-26 13:37
As we plan to release Gravitee.io 3.x, we are re-organizing pages.

Docs for APIM 1.x is available at https://docs.gravitee.io/apim/1.x/apim_installguide_repositories_jdbc.html

Sorry for the inconvenience!
