### ISSUE TITLE
[policy] [transform-headers] First header ignored

### ISSUE THREAD

**Issue by pletessier** [gravitee-io/issues#1444] opened 2018-08-23 16:16 UTC
### Expected Behavior
All "added headers" are received by the managed API.

### Current Behavior
The first header element is ignored, and only the next ones are received.

### Your Environment
Docker, APIM 1.18.1

**Comment by brasseld** [comment] 2018-08-23 16:44
Hello @pletessier,

Please share your API definition.

Thanks

**Comment by brasseld** [comment] 2018-08-23 16:50
I've added a unit tests in the policy and I'm not able to reproduce the issue.

If there is an issue, it may comes from the UI or, perhaps, the way data are deserialized from json to java....

**Comment by pletessier** [comment] 2018-08-24 08:29
Here is my API definition : 
```
{
  "id" : "e947c98d-0b8a-4bc7-87c9-8d0b8a9bc710",
  "name" : "My API",
  "version" : "1",
  "description" : "API description",
  "visibility" : "private",
  "state" : "started",
  "tags" : [ ],
  "context_path" : "/entities",
  "proxy" : {
    "context_path" : "/entities",
    "strip_context_path" : false,
    "loggingMode" : "NONE",
    "groups" : [ {
      "name" : "default",
      "endpoints" : [ {
        "name" : "default",
        "target" : "http://my-api:8080/",
        "weight" : 1,
        "backup" : false,
        "type" : "HTTP",
        "http" : {
          "connectTimeout" : 5000,
          "idleTimeout" : 60000,
          "keepAlive" : true,
          "readTimeout" : 10000,
          "pipelining" : false,
          "maxConcurrentConnections" : 100,
          "useCompression" : true,
          "followRedirects" : false
        }
      } ],
      "load_balancing" : {
        "type" : "ROUND_ROBIN"
      }
    } ]
  },
  "paths" : {
    "/entities/:id" : [ {
      "methods" : [ "DELETE" ],
      "oauth2" : {"extractPayload":true,"checkRequiredScopes":true,"requiredScopes":["run"],"oauthResource":"AM"},
      "description" : "Description of the OAuth2 Gravitee Policy",
      "enabled" : false
    }, {
      "methods" : [ "GET" ],
      "oauth2" : {"extractPayload":false,"checkRequiredScopes":false,"requiredScopes":["catch"],"oauthResource":"AM"},
      "description" : "Description of the OAuth2 Gravitee Policy",
      "enabled" : false
    }, {
      "methods" : [ "POST", "PUT" ],
      "oauth2" : {"extractPayload":true,"checkRequiredScopes":true,"requiredScopes":["run"],"oauthResource":"AM"},
      "description" : "Description of the OAuth2 Gravitee Policy",
      "enabled" : false
    }, {
      "methods" : [ "GET" ],
      "policy-openid-userinfo" : {"extractPayload":false,"oauthResource":"AM"},
      "description" : "Description of the OpenID Connect - UserInfo  Gravitee Policy",
      "enabled" : false
    }, {
      "methods" : [ "GET", "POST", "PUT", "DELETE", "HEAD", "PATCH", "OPTIONS", "TRACE", "CONNECT" ],
      "transform-headers" : {"scope":"REQUEST","removeHeaders":[],"addHeaders":[{"name":"aaaaaaaaaaaaa","value":"aaaaaaaaaaaaa"},{"name":"bbbbbbbbbbbbbbb","value":"bbbbbbbbbbbbbbb"},{"name":"ccccccccccccccc","value":"cccccccccccccc"}]},
      "description" : "Description of the Transform Headers Gravitee Policy",
      "enabled" : true
    } ],
    "/entities/" : [ ],
    "/entities" : [ ],
    "/" : [ ]
  },
  "deployed_at" : 1535098850833,
  "created_at" : 1534854465484,
  "updated_at" : 1535098870955,
  "owner" : {
    "id" : "1effd6f1-b741-44aa-bfd6-f1b74194aa1a",
    "displayName" : "admin"
  },
  "properties" : [ ],
  "services" : { },
  "picture_url" : "http://my-api/management/apis/e947c98d-0b8a-4bc7-87c9-8d0b8a9bc710/picture",
  "resources" : [ {
    "name" : "AM",
    "type" : "oauth2-am-resource",
    "enabled" : true,
    "configuration" : {"clientId":"clientId","clientSecret":"client-secret","securityDomain":"domain","serverURL":"http://am-gateway:8092","version":"V2_X"}
  } ],
  "path_mappings" : [ ]
}
```

**Comment by brasseld** [comment] 2018-10-16 06:01
This issue was caused by the fact that group and endpoint have the exact same name which must be avoid.

Will be resolved by https://github.com/gravitee-io/issues/issues/1578

**Closed by brasseld** 2018-10-16 06:01 UTC
