### ISSUE TITLE
[portal] Add a message on all blank page

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/issues#97] opened 2016-06-26 12:18 UTC
Some pages are blank when no data have to be displayed (API-keys, documentation, ... ).
I think we should provide a message like : 
"Click on the (+) on the bottom-right corner to add a new page/apikey/...)

The (+) should be the blue button and should be clickable.

**Comment by brasseld** [comment] 2016-10-18 07:11
Duplicate of gravitee-io/issues#247

**Closed by brasseld** 2016-10-18 07:11 UTC
Labels: type: duplicate, type: enhancement
