### ISSUE TITLE
Deploy EE version on nigthly build

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#7361] opened 2022-03-23 09:51 UTC
Some modules are only available in EE edition, currently it's impossible to properly test those because we don't have any env with EE version deployed

Need to change our CI workflow and a license to put EE version on our helm deployment

**Comment by Novachevski** [comment] 2022-03-23 10:06
So is this ticket duplicate of https://graviteedevops.atlassian.net/browse/TT-1152

**Comment by ppgravitee** [comment] 2022-03-23 10:21
Not if QA need a dedicated env

**Closed** 2022-07-08 12:39 UTC
Labels: type: technical, project: APIM, wontfix
