### ISSUE TITLE
[gateway] Health check does not pull out unhealthy endpoints

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/issues#7250] opened 2022-03-08 08:46 UTC
## :collision: Describe the bug
While enabling the Health Check at the API level which is looking for a 200 HTTP status and changed the response of one of the endpoints to return a 403, this later is not pulled out of the endpoints pool.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Import the attached API export
2. Start the API
3. Check the API health checks failing on /echo
4. Call the gateway on /echo and notice that the "echo" endpoint is still called

## :rainbow: Expected behaviour

The "echo" endpoint should be pulled out of the endpoints pool and so not called by the gateway.

## Current behaviour

The "echo" endpoint is kept on the pool and still called by the gateway even if the health check is failing.

## :movie_camera: Useful information

[API-Echo-1.txt](https://github.com/gravitee-io/issues/files/8204243/API-Echo-1.txt)

## :computer: Desktop:

***Please complete the following information:***
 - Environment: [e.g. 3.10.x] 3.15.0 and 3.15.4

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

Issue reported here: https://community.gravitee.io/t/health-check-load-balancing-not-failing-over/174

**Comment by mouligno** [comment] 2022-03-08 08:52
Could it be linked to https://github.com/gravitee-io/issues/issues/7135 ?

**Comment by aelamrani** [comment] 2022-03-08 12:07
This bug also appears on 3.13.0 and 3.13.3

**Comment by gcusnieux** [comment] 2022-03-08 12:17
> This bug also appears on 3.13.0 and 3.13.3

Yes it's since SME

**Comment by gaetanmaisse** [comment] 2022-03-09 08:08
Closing as duplicate of https://github.com/gravitee-io/issues/issues/7135

**Closed by gaetanmaisse** 2022-03-09 08:08 UTC
Labels: type: bug, project: APIM, p1, dark matter
