### ISSUE TITLE
[management][dictionaries] Change the way dictionaries id are managed

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5267] opened 2021-03-18 14:32 UTC
The id of a dictionary is generated from its name. This is a problem in a multi-environment context because it won't be possible to have 2 dictionaries with the same name in 2 different environments.

**Comment by aelamrani** [comment] 2021-03-18 14:43
Duplicate of https://github.com/gravitee-io/issues/issues/5073 ?

**Closed** 2021-03-18 15:20 UTC
Labels: project: APIM, type: bug
