### ISSUE TITLE
[feature][policy] way to conditionally activate different policies

### ISSUE THREAD

**Issue by chicco785** [gravitee-io/issues#2433] opened 2019-07-06 03:50 UTC
suppose you have two policies that should be alternatively activated based on some conditions (e.g. on the existence of a given header attribute). is there an easy way to achieve that?

**Comment by brasseld** [comment] 2019-07-10 05:59
Hi @chicco785 

There is currently no way to achieve such thing.
We have an (very) old issue about conditional policies: https://github.com/gravitee-io/issues/issues/60

**Comment by aelamrani** [comment] 2019-09-10 08:17
Duplicate of https://github.com/gravitee-io/issues/issues/60

**Closed by aelamrani** 2019-09-10 08:17 UTC
Labels: project: APIM, type: feature
