### ISSUE TITLE
[management-api] Analytics - api key shown instead of application name

### ISSUE THREAD

**Issue by vdelattre** [gravitee-io/issues#233] opened 2016-09-30 12:10 UTC
Version : 0.19

I created new application and affected an api key for an api.
In analytics of api, name of this application is not shown, but it's look like its apiKey
![image](https://cloud.githubusercontent.com/assets/22543323/18991246/8ed404ee-8717-11e6-8e11-cf75b2e79695.png)

**Comment by brasseld** [comment] 2016-09-30 12:16
Duplicate of gravitee-io/issues#193

**Closed by brasseld** 2016-09-30 12:16 UTC
Labels: type: bug, type: duplicate
