### ISSUE TITLE
[APIM Management] No logs are present on the Response on the Consumer side in Analytics of an API

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#6641] opened 2021-11-26 15:50 UTC
### Expected Behavior
There should be logs on both Request and Response of the Gateway and Consumer side.

### Current Behavior
No logs are present on the Response on the Consumer side in Analytics of an API 

### Steps to Reproduce (for bugs)
1. Create or Import any API.
2. Test the API through Postman
3. Go to the Logs in Analytics in the API
4. No logs will be present on the Response on the Consumer side. Testes or more APIs

![image](https://user-images.githubusercontent.com/57534152/143605141-e6e36b13-4421-4825-8189-22acfb1f0e34.png)

![image](https://user-images.githubusercontent.com/57534152/143605315-476072b2-563b-4dd7-8c93-989202917797.png)

### Your Environment
* Version used: 3.10.7 and 3.12.4 on Docker-Desktop
* Operating System and version: Windows 10

**Comment by mouligno** [comment] 2021-11-26 16:24
Closed since it's duplicate of #6596

**Closed by mouligno** 2021-11-26 16:24 UTC
Labels: type: bug, project: APIM, Support 2
