### ISSUE TITLE
Multiple values of Transaction header when `handlers` is set

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7618] opened 2022-05-03 10:11 UTC
# Describe the bug

When you set "handlers" setting in the gateway gravitee.yml file, the header is duplicated on the response. Here is the setting in the gravitee.yml:

<div class="code panel" style="border-width: 1px;"> 
 <div class="codeContent panelContent"> 
  <pre class="code-yaml"><span class="code-keyword">gravitee: </span>  <span class="code-keyword">handlers: </span>    <span class="code-keyword">request: </span>      <span class="code-keyword">format: </span>uuid
  <span class="code-keyword">request: </span>    <span class="code-keyword">header: </span>X-Custom-Flow-ID
  <span class="code-keyword">transaction: </span>    <span class="code-keyword">header: </span>X-Custom-Flow-ID</pre> 
 </div> 
</div>

# To Reproduce

Steps to reproduce the behaviour: 

*   Create new installation with the configuration mentioned above set in the gateway gravitee.yml.
*   Create 2 APIs. API 2 is the backend of API1
*   Enable logging to see the headers after the call on the API1
*   Make a curl/postman call on API
*   Check the call headers on the response.

# Expected behaviour

There should be only one of the X-`Custom`-Flow-ID header (create 1 if not existent, overwrite if backend sends one)

# Current behaviour

If the backend sends the X-`Custom`-Flow-ID header, it is not overwritten by the gateway, a second header appears instead.

**Comment by gaetanmaisse** [comment] 2022-08-19 14:39
New behavior is due to https://github.com/gravitee-io/issues/issues/7325

**Comment by gaetanmaisse** [comment] 2022-08-19 15:33
After investigation we discussed some potential options: 

#### 1. Consider the new/current behavior as the expected one

Headers set with policies and by the gateway are always "concatenated" with the ones of the proxy response. 
Thus, the response from the gateway can contain a header with multiple values (displayed as multiple headers in the UI)

![image](https://user-images.githubusercontent.com/4112568/185652791-a1b210af-b3bc-4fbd-9782-57988f8795f2.png)


#### 2. Change the code to add transaction + request id headers only if they are not present on the response

Currently everything related to transaction and request ids is done in the `TransactionProcessor` https://github.com/gravitee-io/gravitee-api-management/blob/b75d0b0919a4a7f17528d1d1c68daefac9dfcb11/gravitee-apim-gateway/gravitee-apim-gateway-reactor/src/main/java/io/gravitee/gateway/reactor/processor/transaction/TransactionProcessor.java which is called before the request is made (as part of the `requestProcessorChainFactory`).

It means when the proxy response is handled, the gateway adds the proxy response headers to the one already set by the `TransactionProcessor`.  

The proposed refactoring would lead to set transaction + request id headers on the request at the beginning of the process and add them to the response at the end. To do so, we have in mind to:
 - Split the `TransactionProcessor` into `TransactionRequestProcessor` and `TransactionResponseProcessor`
 - The `TransactionRequestProcessor` would be responsible for setting the transaction and request id headers on the request. It will be part of the `requestProcessorChainFactory`
 - The `TransactionResponseProcessor` would be responsible for setting the transaction and request id headers on the response IF they weren't already provided in the proxy response. It will be part of the `responseProcessorChainFactory`

---

🗣️ We would like to hear @brasseld and @gravitee-io/apim feedback before changing any code

**Comment by jhaeyaert** [comment] 2022-09-19 06:50
@gaetanmaisse lets discuss it as I'm not sure to really understand the expected behavior, especially the fact the the X-Flow-Id is set by the gateway at request stage but is also returned by the backend endpoint but with a different value and so, I'm not sure it makes sense to override it 🧐
We should also pay attention to make that behavior the same for te Jupiter engine.

**Comment by kirestoj01** [comment] 2022-12-14 11:43
Another client reported same issue.

**Comment by gaetanmaisse** [comment] 2023-01-24 14:42
After a discussion with @jhaeyaert we end up with the following proposal:

To avoid introducing another breaking change it would be interesting to let the users pick the behavior they want when the backend of the API is also setting the `request` or `transaction` header. So, the configuration will be updated to something like this:

```yaml
gravitee:
  handlers:
    request:
      format: uuid
      request:
        header: X-INVERS-Flow-ID
        # ⬇️ This is a new attribute
        overrideMode: none 
      transaction:
        header: X-INVERS-Flow-ID
        # ⬇️  This is a new attribute
        overrideMode: none
```

Possible values of `overrideMode` are the following:
 - `none`: The header set by the APIM Gateway will be kept and the one provided by the backend discarded 
 - `merge`: Both headers set by the APIM Gateway and the backend will be kept (as headers can be multi valued)
 - `override`: The header set by the APIM Gateway will be overridden by the one provided by the backend

**Closed** 2023-03-15 15:49 UTC
Labels: type: bug, project: APIM, Support 3, p2, p4, Geckos, archpim
