### ISSUE TITLE
Incorrect rendering of swagger on UI

### ISSUE THREAD

**Issue by AnnaNKorotkova** [gravitee-io/issues#8638] opened 2022-11-08 08:35 UTC
## :collision: Describe the bug
Incorrect rendering of swagger on UI. When we specify "required: false" in swagger rendered as a required field. 

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1\. add swagger file into portal
with paraments
  parameters:
    Limit:
      name: limit
      description: Maximum size of the received list of transactions
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 20
    Offset:
      name: offset
      description: Size offset from the beginning of the list of transactions. If the parameter is out of selection range, an empty array is returned
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 0

## :rainbow: Expected behaviour
I expect that the field will be marked optional. 

## Current behaviour
I expect that the field marked required

**Comment by AnnaNKorotkova** [comment] 2022-11-08 08:37
If I delete required: false It doesn't change anything

**Comment by brasseld** [comment] 2023-02-23 13:00
Duplicate of https://github.com/gravitee-io/issues/issues/8634

**Closed by brasseld** 2023-02-23 13:00 UTC
Labels: type: bug, project: APIM, p4
