### ISSUE TITLE
Propogate API key is not working

### ISSUE THREAD

**Issue by Sivamani180915** [gravitee-io/issues#1147] opened 2018-03-16 06:03 UTC
### Expected Behavior

We can able to access the API key in the Endponit.
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:1.14
* Browser Name and version:All
* Operating System and version:Windows

**Comment by brasseld** [comment] 2018-07-06 09:58
Duplicate of https://github.com/gravitee-io/issues/issues/1363

**Closed by brasseld** 2018-07-06 09:58 UTC
