### ISSUE TITLE
[APIM Portal] When importing a swagger document only in .yml format the data is not the same on the Console UI preview and on the Portal. Issue is in the Portal.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7510] opened 2022-04-13 14:57 UTC
## :collision: Describe the bug
When we import a swagger page to our API the data is not the same when we compare what is displayed in editor.swagger.io, Portal and Console. To be more specific the correct display of information is in the Console UI and editor.swagger.io while the issue is in the Portal. If this .yml document is converted to json there is no issue.

## :sunrise_over_mountains: To Reproduce
1. Create/Import simple API.
2. Import the swagger file give bellow.
3. Go to Schemas -> Test. Both on Console and Portal UI

![image](https://user-images.githubusercontent.com/57534152/163209190-b6069c35-30ef-4d76-b903-38f262f43da1.png)

![image](https://user-images.githubusercontent.com/57534152/163209294-27382d3c-45a9-4780-b7a7-a052ebb42a49.png)

The correct value should be NO while on the Portal is False

## :rainbow: Expected behavior
Data should be the same both In Portal and Console.

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material
Contact me for file.

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts:

***What are the impacted versions?***
- 3.15.6, 3.15.7, 3.16.1

gz#4019

**Comment by mouligno** [comment] 2022-07-15 09:26
`NO` is a reserved Keyword in yaml. 

It can be properly interpreted using quotes : 
```    
enum:
        - 'NO'
```

**Comment by apoddany** [comment] 2022-07-19 09:25
@marijatimovska to be checked

**Comment by mouligno** [comment] 2022-12-30 13:25
@marijatimovska did you check ?

**Comment by gaetanmaisse** [comment] 2023-01-31 13:33
Closing as the info provided in https://github.com/gravitee-io/issues/issues/7510#issuecomment-1185357471 is right and seems to be the root cause.

**Closed by gaetanmaisse** 2023-01-31 13:33 UTC
Labels: type: bug, project: APIM, more-information-needed, Support 3, p3
