### ISSUE TITLE
[management-api] Can't save settings

### ISSUE THREAD

**Issue by yazalulloa** [gravitee-io/issues#2906] opened 2019-11-19 22:53 UTC
I upgraded Gravitee APIM to 1.30.0 from 1.29.6 and when I try to change anything in the settings menu it returns an error.

I'm running Gravitee APIM 1.30.0 with MongoDB 3.4 and Elasticsearch 5.4.3 in Docker

Here is the error in the UI
![image](https://user-images.githubusercontent.com/33322056/69193391-f532b980-0afc-11ea-83e4-180745250993.png)

This is the server response
![image](https://user-images.githubusercontent.com/33322056/69193463-1dbab380-0afd-11ea-9540-7a30dd2ab810.png)

Here is the request json
[request.zip](https://github.com/gravitee-io/issues/files/3866431/request.zip)

**Comment by brasseld** [comment] 2019-11-20 08:35
Hey @yazalulloa 

I think it is due to your constants.json.

Probably a duplicate of https://github.com/gravitee-io/issues/issues/2473

Thanks for your feedback.

**Comment by yazalulloa** [comment] 2019-11-20 13:12
> Hey @yazalulloa
> 
> I think it is due to your constants.json.
> 
> Probably a duplicate of #2473
> 
> Thanks for your feedback.

I remove the dashboard from tag from my contants.json, it works fine now

**Comment by brasseld** [comment] 2019-11-20 13:18
Thanks for your feedback !

**Closed by brasseld** 2019-11-20 13:18 UTC
Labels: project: APIM, type: duplicate
