### ISSUE TITLE
Unauthenticated user will be redirect to login form when receive activation mail

### ISSUE THREAD

**Issue by Tr4m4** [gravitee-io/issues#2695] opened 2019-10-02 09:22 UTC
When the user receive the activation mail and click on "activation link" the browser will be open and go to url like this:

https://****/gateway/#!/resetPassword/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZTJkY2Q4NS00OGE3LTQ2MTktYWRjZC04NTQ4YTcxNjE5MWYiLCJmaXJzdG5hbWUiOiJNYXVybyIsImlzcyI6ImdyYXZpdGVlLW1hbmFnZW1lbnQtYXV0aCIsImFjdGlvbiI6IlJFU0VUX1BBU1NXT1JEIiwiZXhwIjoxNTcwMDkxNjQxLCJpYXQiOjE1NzAwMDUyNDEsImVtYWlsIjoibWF1cm8udHJhcGFuaUBnbWFpbC5jb20iLCJqdGkiOiJjMTk5MjBiOS1hOGE1LTQxZDAtYjk1MC01YTYyODI0MmVhZjkiLCJsYXN0bmFtZSI6IlRyYXBhbmkifQ.vNwX7RPfJqzK4UL3t_VJUzY7DwfGeyDC9YjhtQwDklo

When the browser finish to load UI the user will be redirect to:

https://****/gateway/#!/login

and cann't activate account.

Gravitee is installed with docker official image, and the version is 1.24.0

Thanks

**Comment by aelamrani** [comment] 2019-10-02 19:26
@Tr4m4 Please share an error or a stack trace.

**Comment by Tr4m4** [comment] 2019-10-03 12:31
i don't found any logs, i checked:
- gravitee.log
- gravitee_accesslog_2019_10_03.log
of the managementapi.
Anything else to check?

The problem is open url:
![image](https://user-images.githubusercontent.com/56069731/66126670-4d176e80-e5ea-11e9-93c3-eaf2c4d96a0b.png)

redirect to login:
![image](https://user-images.githubusercontent.com/56069731/66126687-59033080-e5ea-11e9-9981-d58f726ef023.png)

If i'm already logged in, it's work without problem

**Comment by aelamrani** [comment] 2019-10-03 13:06
I do not really understand what you are trying to do.

You said that you are trying to activate your account but depending on the URL, you are resetting your password.

So, after this reset, it is perfectly normal to be redirected to the login form.

**Comment by Tr4m4** [comment] 2019-10-03 13:21
The reset should redirect to form for change password, right?
If i try with an authenticated session, it's happen, i can change password. 
If i try with an unathenticated session (maybe i don't remember password) it's doesn't happen, it's redirect to login form cleaning the query param of the reset URI

The behavior for activation is the same.

**Comment by aelamrani** [comment] 2019-10-03 13:31
I'm not able to reproduce on version 1.25.

As the 1.24 is not supported anymore, are you able to upgrade?

**Comment by Tr4m4** [comment] 2019-10-03 13:53
Not now, i must scheduler a down time and communicate to every users.
You can close the issue as unresolved if you have SLA time.
Thanks for your help, i hope it will be fix with an upgrade of software.

**Comment by aelamrani** [comment] 2019-10-03 14:00
Ok, the i close it. 
Feel free to re-open it if you are able to reproduce on 1.25 version.

**Closed by aelamrani** 2019-10-03 14:00 UTC
