### ISSUE TITLE
 [management-ui] Failed CSS loader at yarn run serve:dist

### ISSUE THREAD

**Issue by loveslikey** [gravitee-io/issues#1661] opened 2018-11-14 03:33 UTC
Expected Behavior
Expected behavior would be yarn run serve:dist running without erros and displaying the local URL as in 'localhost:3000' .

Current Behavior
**Executing yarn run serve:dist throws the following error.**
---------------------------------------------------------------------------------------------------------

> @ ./src/management/management.module.ts 207:41-117
 @ ./src/index.ts

ERROR in ./src/index.scss 4:0
Module parse failed: Unexpected character '@' (4:0)
You may need an appropriate loader to handle this file type.
| $backgroundColor: rgb(45, 50, 62);
|
> @import '~angular-loading-bar/build/loading-bar.css';
| @import '~angular-material/modules/scss/angular-material';
| @import '~angular-material-data-table/dist/md-data-table.css';
 @ ./src/index.ts 23:0-23
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  5.97 KiB       0
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 2.37 KiB {0} [built]

---------------------------------------------------------------------------------------------------------

npm install --global --production windows-build-tools has been executed as described in the readme before running yarn install

Possible Solution
Steps to Reproduce (for bugs)
Clone https://github.com/gravitee-io/gravitee-management-webui.git
Install http://nodejs.org[nodejs], it comes with http://npmjs.org[npm]
Install https://yarnpkg.com[yarn]
run npm install --global --production windows-build-tools
run yarn install
run yarn run serve:dist

**Your Environment**
Node version: v10.13.0
Yarn version:1.12.3
NPM version is 6.4.1
Version used: WebUI 1.20.4
Operating System and version: windows 7,8 2008

**Comment by brasseld** [comment] 2018-11-14 07:15
Duplicate of https://github.com/gravitee-io/issues/issues/1512

Someone has already provided a patch for this.

Your feedback is very welcome if you can confirm the fix is working well.

**Closed by brasseld** 2018-11-14 07:15 UTC

**Comment by NicolasGeraud** [comment] 2018-11-15 08:44
hi @loveslikey ,

have you been able to try the pull request pointed by david ?
