### ISSUE TITLE
Api setting "Enable compression (gzip, deflate)" no longer works?

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#8605] opened 2022-10-26 12:19 UTC
## :collision: Describe the bug
Since version 3.15.6 regardless of setting API "Enable compression (gzip, deflate)" , there is no header Accept-Encoding
in version 3.15.5 everything is OK, Accept-Encoding header exists

API option "Enable compression (gzip, deflate)" enabled
![image](https://user-images.githubusercontent.com/26620272/198012161-e6254b50-70fb-47fc-844e-16429847499b.png)
version 3.15.6, 3.15.16, 3.19.1 missing Accept-Encoding header
![image](https://user-images.githubusercontent.com/26620272/198015536-f97445ed-3a60-4684-a570-3f51ce0dcf42.png)
in version 3.15.5 everything is OK, Accept-Encoding header exists
![image](https://user-images.githubusercontent.com/26620272/198015401-2aff03a7-5cab-4197-bd84-7b9f144354cb.png)

the problem is probably due to this commit [https://github.com/gravitee-io/gravitee-connector-http/commit/c56454bbfbf8fc72d430650c6dd61d73cac8f9dc](url)

**Comment by brasseld** [comment] 2022-10-26 12:21
Hello @grignix 

Probably a duplicate of https://github.com/gravitee-io/issues/issues/7935 which has been fixed and will be integrated to the next 3.15.x version.

**Closed** 2022-10-28 12:40 UTC
Labels: type: bug
