### ISSUE TITLE
Helm, how add envs and organizations to gateway

### ISSUE THREAD

**Issue by allanian** [gravitee-io/issues#8418] opened 2022-09-06 13:30 UTC
Hello,
I need to configure 2 organizations, like
- test1
- test2

and 3 envs, like:
- dev
- stg
- prod
How i can do that from the helm chart?

**Comment by gaetanmaisse** [comment] 2023-02-02 08:36
Closing as it feels unclear and the issue is quite old. Feels free to reopen it and provide more of your context.

**Closed by gaetanmaisse** 2023-02-02 08:36 UTC
Labels: type: bug, more-information-needed, Helm
