### ISSUE TITLE
[APIM][Portal UI] Metadata format dropdown menu will not show completely unless there are many rows added

### ISSUE THREAD

**Issue by kirestoj01** [gravitee-io/issues#7240] opened 2022-03-04 11:36 UTC
1.  <g-emoji class="g-emoji" alias="boom" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4a5.png">
     💥 
     </g-emoji> Describe the bug Metadata format dropdown menu will not show completely unless there are many rows added. Appears too small and you have to scroll through it.
2.  <g-emoji class="g-emoji" alias="sunrise_over_mountains" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f304.png">
     🌄 
     </g-emoji> To Reproduce Steps to reproduce the behaviour: 1\. Go to portal > Select Application > Go to Metadata tab 2\. Click on the dropdown format menu.
3.  <g-emoji class="g-emoji" alias="rainbow" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f308.png">
     🌈 
     </g-emoji> Expected behaviour When you click the dropdown menu it should show at least few options without the need of scrolling like it does if there are more rows of metadata added.
4.  <g-emoji class="g-emoji" alias="movie_camera" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f3a5.png">
     🎥 
     </g-emoji> Useful information

[https://user-images.githubusercontent.com/98313939/156756290-43cd7504-e8fc-4656-9cbb-83e20bf77e86.mp4](https://user-images.githubusercontent.com/98313939/156756290-43cd7504-e8fc-4656-9cbb-83e20bf77e86.mp4)

[https://user-images.githubusercontent.com/98313939/156756388-bf61313b-f7ea-490c-bfe8-aa94f9e6872f.mp4](https://user-images.githubusercontent.com/98313939/156756388-bf61313b-f7ea-490c-bfe8-aa94f9e6872f.mp4)

1.  <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">
     💻 
     </g-emoji> Desktop:

 _**Please complete the following information:**_ 

*   Environment: 3.10.10
*   OS: Docker Installation
*   Browser Chrome

1.  <g-emoji class="g-emoji" alias="warning" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a0.png">
     ⚠️ 
     </g-emoji> Potential impacts

 _**Which other features may be impacted by this fix. This could be populated after fix**_ 

 _**What are the impacted versions?**_ 

1.  <g-emoji class="g-emoji" alias="link" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f517.png">
     🔗 
     </g-emoji> Dependencies

Link a story or other related things...

**Comment by gaetanmaisse** [comment] 2023-04-03 06:36
Closing as duplicate of https://github.com/gravitee-io/issues/issues/8348 which has been fixed in the latest versions of APIM

**Closed** 2023-06-08 12:23 UTC
Labels: type: bug, project: APIM, Trigger Exalate
