### ISSUE TITLE
[AM-IDPs]Not able to update user attributes withing IDP(HTTP) after a user has been created/authenticated.

### ISSUE THREAD

**Issue by marijatimovska** [gravitee-io/issues#7647] opened 2022-05-12 13:55 UTC
## :collision: Describe the bug
When we create a user via any IDP within AM and later we want to update the information we are not able to. If we want for example to change the email after the user has been created the information will not automatically change when we update the email here:

![image](https://user-images.githubusercontent.com/57534152/168089592-8b0eaf40-5d47-4d36-a999-eb68030fad3d.png)

We would need to delete the old attribute and create a new one with the changed value.

If we try to do a modification of the back end of the HTTP provider and later authenticate we get the same behavior.

## :sunrise_over_mountains: To Reproduce
1. Go to Users -> Create a user using Default IDP(MongoDB)
2. Update any of the field like firstname, lastname or email and you will see they to not change after a save, the old value will stay.

## :rainbow: Expected behavior
If we want to update information from the user like name, email, lastname and we do it in here:

![image](https://user-images.githubusercontent.com/57534152/168090250-ca1a06ab-6fcd-4245-92db-228813660a6a.png)
 
The same data should sync up and update in the attributes bellow instead of us doing it by hand or deleting and creating the user from the begining

## :computer: Desktop:

***Please complete the following information:***
 - Environment: Docker-Desktop
 - OS: Windows 11
 - Browser: Google Chrome

## :warning: Potential impacts

***What are the impacted versions?***
- 3.17.2, present in older version also

**Comment by farmborough** [comment] 2022-05-20 07:54
Duplicate of [7531](https://app.zenhub.com/workspaces/graviteeio---access-management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7531)

**Closed by farmborough** 2022-05-20 07:54 UTC
Labels: type: bug, project: AM, Support 3
