### ISSUE TITLE
Issues when sending emails from Gravitee platform

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#7029] opened 2022-01-31 11:31 UTC
After the update of Gravitee to version 3.15.0, there are issues while sending out emails from Gravitee.

Before the update, these issues did no occur. It seems to be that a specific PNG image is not available anymore on the Docker Image that's loaded. See the attached file(s) for more details.

Steps to reproduce the behaviour:
1. Tried to get an email from the platform
2. The error that occurs:

[manapilogs.txt](https://github.com/gravitee-io/issues/files/7970339/manapilogs.txt)

Used versions: APIM 3.15.0

**Comment by apoddany** [comment] 2022-02-07 16:14
closing as duplicate of #7057

**Closed by apoddany** 2022-02-07 16:14 UTC
Labels: type: bug, project: APIM, Support 2
