### ISSUE TITLE
[portal] Bad API rating from catalog

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#3423] opened 2020-04-04 05:44 UTC
Stars are not accurate

<img width="1445" alt="Capture d’écran 2020-04-04 à 07 44 09" src="https://user-images.githubusercontent.com/133094/78419662-28a75800-7648-11ea-9bf1-a78073cabffc.png">
<img width="366" alt="Capture d’écran 2020-04-04 à 07 44 22" src="https://user-images.githubusercontent.com/133094/78419664-2a711b80-7648-11ea-9242-3220d866b93c.png">

**Comment by aelamrani** [comment] 2020-04-04 06:25
Duplicate of https://github.com/gravitee-io/issues/issues/3364

**Closed by aelamrani** 2020-04-04 06:25 UTC
Labels: project: APIM, type: uat
