### ISSUE TITLE
[management] User Search Modal only finds user in memory

### ISSUE THREAD

**Issue by manuelottlik** [gravitee-io/issues#2606] opened 2019-09-12 12:23 UTC
When searching for a user in the management-ui via the user search modal users that are not from source "memory" won't be found.

### Expected Behavior
Searching for a user should include all sources.

### Current Behavior
When searching for a user in the management-ui via the user search modal users that are not from source "memory" won't be found.

### Possible Solution
search in all sources. the problem does not seem to be in the frontend, the query is submitted to the server correctly but an empty array is returned.

### Steps to Reproduce (for bugs)
1. go to user management > groups in the management-ui
2. click add member
3. search for a user not stored in the memory source

### Context
I am trying to add a user to a group, API, or application.

### Your Environment
* Version used: 1.28.1
* Browser Name and version: Chrome 76.0.3809.100
* Operating System and version: macOS 10.14.6

**Comment by manuelottlik** [comment] 2019-09-26 12:43
The default gravitee source for example, the one users are created in by default. I would also expect it to show users imported by Client Registration Providers.

**Comment by brasseld** [comment] 2019-09-26 13:17
Client Registration is used for Oauth2 client, and these are not end-users, so there is absolutely no reason to get them from search modal.

**Comment by gigo1980** [comment] 2019-10-17 09:04
As discussed with @brasseld this happens also to OAuth Users that are already logged into Gravitee and the users are shown in the Gravitee User Management. So the users are referenced in the internal Gravitee Database but are not searchable in any user search Modal.

Please investigate the issue again.

**Comment by gigo1980** [comment] 2019-10-18 06:09
@brasseld: I think your bot is doing strange things

**Comment by aelamrani** [comment] 2019-10-18 06:14
Bots are taking control

**Comment by manuelottlik** [comment] 2019-10-18 09:27
I guess the bot wants **me** to reply to this - here you go 🤖

**Comment by brasseld** [comment] 2019-10-18 11:28
Good job :)

**Comment by manuelottlik** [comment] 2019-10-29 12:03
Can you give me an estimate on when this feature will be implemented? Is it scheduled for a release already? It's basically impossible to use platform since we can't assign permissions to anyone ☹️

**Comment by brasseld** [comment] 2019-10-29 13:09
Hi @manuelottlik / @gigo1980 

So I had a quick look to this issue and I have to admit that I don't understand.

Here is what I've done:

- Start a new keycloak instance with a Portal realm
- Add a user 
- Add Keycloak authentication provider in Gravitee
- Login to the portal with the created user (to store it into storage)
- Login to the portal with an other account (admin)
- Go to an API > members
- Search for the created user

And I'm able to see this later...

Perhaps I'm wrong or I missed something...

**Comment by manuelottlik** [comment] 2019-10-30 11:47
Hi @brasseld,

first of all thank you for looking into this that detailed!
In our deployment of Gravitee it even occurs on users that are created in the *gravitee* source.
Even though we updated all images this still occurs - maybe the problem is located in some database structure of mongodb that has not been updated accordingly.

However, since we are migrating to a different deployment infrastructure kinda soon (where we have set up Gravitee from ground up) we tried to search for a user in this newer deployment and it works! Therefore, we will not look into this issue any further - even though we do not know the cause we know it is fixed in the current version of Gravitee.

Thank you again for looking into this!
I guess this issue can be closed.

**Comment by brasseld** [comment] 2019-10-30 11:59
Hi @manuelottlik 

Thanks this feedback, appreciate it!

There is still one thing I do not understand because when searching for user, this search is done using an underlying Lucene index, and not the repository directly.

So I would assume that there may be some issues with your local Lucene index. For which reason, I don't know, but I'm pretty sure that this is a deployment issue (missing plugin for management-api ?) and that's probably why it works well with a fresh install.

What is strange to me also is that you're the only one who encounters this kind of issue...

Anyway, I close the issue as per your comment since you're no more able to reproduce with a fresh installation.

Thanks a lot!

**Closed by brasseld** 2019-10-30 11:59 UTC
Labels: project: APIM
