### ISSUE TITLE
[policy] [api-key] Policy failures always produce json content

### ISSUE THREAD

**Issue by k-oliver** [gravitee-io/issues#1719] opened 2018-12-05 15:17 UTC
if a policy, for example the api-key policy produces a failure and would set a content type for the PolicyResult the content type is ignored and always overwritten by content type json.

### Expected Behavior
i expected the content type to be recognized. imagine a api key policy that produces xml content in case of a api key failure.

### Current Behavior
the content type is overwritten here: https://github.com/gravitee-io/gravitee-gateway/blob/76bee704a624e2900e3b61c7a7b38f280e3f5332/gravitee-gateway-handlers/gravitee-gateway-handlers-api/src/main/java/io/gravitee/gateway/handlers/api/ApiReactorHandler.java#L235

### Possible Solution
respect the given content type

### Context
my general goal was to change  the content of in invalid api key response which lead me to the question of what happens in case of api key checks in non json endpoints. really great would be a configurable response for the api key policy plugin.

### Your Environment

duplicates #1473

**Comment by k-oliver** [comment] 2018-12-06 09:14
Hi @brasseld ,
1. You are right. in case of the API-key policy the Accept header was my starting point. i send the Accept header application/xml to some endpoint with API-key policy, the API-Key check fails and json content is returned. so the Accept header is not resprected by the API-key policy. this should by changed i guess.

2. Then I looked into the API-key policy to find out what went wrong and got the idea of writing an own policy where i can define the response content matching the current API. so in generell it would be great to have the possibility to define the response payload for all policies that are able to return complete responses (e.g. are calling PolicyChain.failWith(...)). in case of the API-key policy that may be something configurable like
```java
if (errorCaseNoAPIkeygiven) {
  if (accept.equals("application/json") {
    return "{\"some\":"configured payload"}";
  }
  if (accept.equals("application/xml")) {
    return "<some>configured payload</some>"
  }
}
if (errorCaseWrongAPIKey) {
  ....
}
```
so the configurable part may be the different error cases combined with the Accept content type.

**Comment by brasseld** [comment] 2018-12-06 09:20
Hi

1) Duplicate of https://github.com/gravitee-io/issues/issues/1473

2) Duplicate of https://github.com/gravitee-io/issues/issues/972

I think the first point can be resolved pretty easily.
The second one is not so easy because I'm sure that response may be customized for each API and not globally to the platform.

What do you think?

**Comment by k-oliver** [comment] 2018-12-06 09:30
Hi @brasseld ,
1. great!
2. sure. the response should be costomized for each API. so it has to be a configuration for the API-Key policy. for now i will try to write a costom api key policy with configurable payload (only json in this case) and let you know about the result?

**Comment by brasseld** [comment] 2018-12-06 09:35
2. With pleasure !

**Comment by brasseld** [comment] 2018-12-07 16:41
Hello @k-oliver 

Really nice stuff, congrats!

My only concern is about the `Content-Type` property. I don't understand its purpose since we have to rely only on the 'Accept' header to choose for the correct response Content-type.

The other point is about the way to handle multiple error types.
I think that the best is to keep the api-key policy only at the plan level (and not the API as you've done).

Why not providing an all the valid response type within the API-key policy configuration ?

Last point: 
- type of error should not support EL (doesn't make sense)
- idem for response code

**Comment by k-oliver** [comment] 2018-12-09 12:33
Hello @brasseld ,
i changed the last point with https://github.com/k-oliver/gravitee-policy-apikey/commit/27f07ed700a75cf4470a89b231ebc027f93f8b8f.

The purpose of the ``Content-Type`` property is to configure different payloads for different ``Accept`` headers. For example if you have an API that can answer JSON and XML depending on the ``Accept`` header you may want to configure a JSON response content when JSON is requested and XML content if XML is requested. The property ``Content-Type`` is matched against the ``Accept`` header to choose the correct response from the configuration.

The multiple error handling was a work around. I first tried to do all stuff at plan level. BUT: The API-Key policy do not come to execution if no API-Key header is part of the request. See here: https://github.com/gravitee-io/gravitee-gateway/blob/f09b9d526b2c3f65852e6573c0cba7037783001f/gravitee-gateway-security/gravitee-gateway-security-core/src/main/java/io/gravitee/gateway/security/core/SecurityPolicyChainResolver.java#L56
So if no AuthenticationHandler can handle a request the default response is used. I also forked the relevant code and made a change to choose one of the configured AuthentificationHandlers in this case:
https://github.com/k-oliver/gravitee-gateway/commit/2fe85c14ff4712a4624085c16e95bd41e72d0367
This enables a full plan level configuration.

do you agree?

**Comment by brasseld** [comment] 2018-12-10 11:55
Hello @k-oliver 

Sorry for the delay.

I understand the purpose of the content-type, but I would prefer to manage the content-type according to the Accept header (from the request). And, in that case, it will not be specific to the api-key policy only but to all the platform.

Ok, I got your 2).

If we fix the issue about content-type I think it will be easier for you to manage api-key policy's configuration and you will have to take care only about error code from api-key.

WDYT ?

**Comment by k-oliver** [comment] 2018-12-10 14:35
Hey @brasseld ,
I'm not shure if I understood you correct: the content-type is actually managed according to the Accept header from the request. see here: https://github.com/k-oliver/gravitee-policy-apikey/blob/27f07ed700a75cf4470a89b231ebc027f93f8b8f/src/main/java/io/gravitee/policy/apikey/ApiKeyPolicy.java#L146
a current configuration only at plan level for the API-Key policy looks like this (JSON and XML responses depending on the Accept header):
![image](https://user-images.githubusercontent.com/2338960/49738679-d50d4000-fc87-11e8-94bf-0ac0e7da95da.png)
![image](https://user-images.githubusercontent.com/2338960/49738759-1998db80-fc88-11e8-84fd-efab25f02e16.png)


It would be ok for me to remove the content-type property, if you prefer it. Should I?
Then there would be no need to check for the Accept header any more because you can only configure one response for each error type.

A generell configuration outside the API-Key policy would be ok too, but it has to be at plan or API level to be part of the API specification, right?

**Comment by brasseld** [comment] 2018-12-10 15:07
Ok, I didn't understand why you do such thing but now I think I got it.
You have defined a specific response for each content-type, I think that was the missing point (from my side)...

**Comment by brasseld** [comment] 2019-04-11 05:54
Will be done thanks to https://github.com/gravitee-io/issues/issues/972

**Closed by brasseld** 2019-04-11 05:54 UTC
Labels: project: APIM, type: feature
