### ISSUE TITLE
[ui] Health Check Menu is not Shown with only read permissions to "api-health"

### ISSUE THREAD

**Issue by gigo1980** [gravitee-io/issues#2581] opened 2019-09-10 07:18 UTC
If you have a role that have only read permissions the health check endpoint of an API, the menu entry will not be shown.

This has to be changed from "create" to "read".

I will create a pull request for that.

**Comment by aelamrani** [comment] 2019-09-10 07:59
Duplicate of https://github.com/gravitee-io/issues/issues/2566

**Closed by aelamrani** 2019-09-10 07:59 UTC
