### ISSUE TITLE
Both platform level alerts, and api level alerts are not getting triggered

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8669] opened 2022-11-23 14:03 UTC
# Describe the bug 

Create simple api/platform level alert, and it has the same definition platform: !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/203564590-c6a4ddf5-21b0-437e-9e0c-dac1c1014f2b.png](https://user-images.githubusercontent.com/89140082/203564590-c6a4ddf5-21b0-437e-9e0c-dac1c1014f2b.png)) 

api level: !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/203564784-60dbea0c-1e06-429e-84ae-f4e8e15a3e5d.png](https://user-images.githubusercontent.com/89140082/203564784-60dbea0c-1e06-429e-84ae-f4e8e15a3e5d.png))

the call made from postman !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/203565630-66f36dce-d38b-4200-8db3-6c4cc086b28e.png](https://user-images.githubusercontent.com/89140082/203565630-66f36dce-d38b-4200-8db3-6c4cc086b28e.png))

# To Reproduce

Steps to reproduce the behaviour:

1.  Deployed 3.18.12 with connector 1.6.6
2.  Created an API and added both API level and platform-level alerts
3.  Doing a call, both alerts should send a notification; hence the time is 68, and if below, then 200 should fire a notification
4.  No notification is sent for API/platform level alert, and there are no errors in the logs
5.  Seeing the triggers set up in the logs, but not seeing any triggered to send a notification, even it should ... !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/203565432-ec1ed8ad-1d93-4fbe-9545-8ceca630e44f.png](https://user-images.githubusercontent.com/89140082/203565432-ec1ed8ad-1d93-4fbe-9545-8ceca630e44f.png))

# Expected behaviour 

Expected both alerts to fire a notification

# Current behaviour 

no alerts are getting triggered (platform or api lvl) 

*   Environment: <span class="error">[APIM 3.18.12, ws connector 1..6.6]</span>

Additionally: tested with ae 2.0.0 platform level alerts 

-this alert works, platform as well: !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/216294214-d549707f-98c7-46d2-b07b-5c44266c7e7a.png](https://user-images.githubusercontent.com/89140082/216294214-d549707f-98c7-46d2-b07b-5c44266c7e7a.png))

-this is not triggering: !<span class="error">[image]</span>([https://user-images.githubusercontent.com/89140082/216294537-ac98323b-5dc2-464f-a69d-be7f52deeae3.png](https://user-images.githubusercontent.com/89140082/216294537-ac98323b-5dc2-464f-a69d-be7f52deeae3.png)) -with or without the settings used on the filter

-not all platform alerts are failing

**Comment by gaetanmaisse** [comment] 2023-04-13 13:21
Closing as the original problem was a wrong configuration and not a bug with the alert engine

**Closed by gaetanmaisse** 2023-04-13 13:21 UTC
Labels: type: bug, project: APIM, p2, p3
