### ISSUE TITLE
RPM packages delete custom config files on upgarde

### ISSUE THREAD

**Issue by assen-totin** [gravitee-io/issues#5827] opened 2021-07-06 19:58 UTC
### Expected Behavior
`yum update` SHOULD NOT delete any config file that has been manually modified. This is A-B-C of RPM package management, really. 

### Current Behavior
`yum update` DELETED all my custom `gravitee.yml` files in both API products (APIM and gateway, or whatever you call them - do you know your naming is a mess?) which took hours to assemble (due to the need to copy/paste same Mongo/Elastic/Whatever config in multiple YAML files while also taking care for each and every space due to the file format.)

### Possible Solution
- Use `%config(noreplace)` in the spec file for ALL config files. This will AT LEAST preserve the old config file with an `.rpmsave` extension so that it may be copied to the new installation directory. 
- Add a `%post` task in the spec file to do this copy after the upgrade. It is not that hard. 
- Even better, stop placing each new bugfix version in its own named subdirectory and use one and the same for each major release, then update in-place in minor upgrades and bugfix updates.

### Steps to Reproduce (for bugs)
Install 3.9.1 from your repos. Configure it. Upgrade to 3.9.2 via yum. Now all API custom configs are gone, because they re not labelled as config files. 

### Context
This broke my existing installation completely and had me waste hours to recreate the configuration. 

### Your Environment
RedHat Enterprise Linux 8, upgrading from 3.9.1 to 3.9.2.

**Comment by brasseld** [comment] 2021-07-08 08:56
Duplicate of https://github.com/gravitee-io/issues/issues/5287

We are currently working on it.

**Closed by brasseld** 2021-07-08 08:56 UTC
Labels: type: duplicate
