### ISSUE TITLE
HTTP Callout Policy Error Response Body Does Not Support EL

### ISSUE THREAD

**Issue by zdenda-online** [gravitee-io/issues#3376] opened 2020-03-27 07:17 UTC
According to "docs" (description in the UI app) in AM Extension points, the error response body supports EL (the form says: _The body response of the error if the condition is true (support EL)_). Actually it does not support it. 

### Expected Behavior
AM Extension point HTTP Callout will have correct description (so that it does not support EL) or will support EL (which is better option)

### Current Behavior
Form says it supports EL but it does not work.

### Possible Solution
Call EL in HTTP callout policy. Currently there is this code in `CalloutPolicyHttp`

```
 String errorContent = configuration.getErrorContent();

if (errorContent == null || errorContent.isEmpty()) {
    errorContent = "Request is terminated.";
}

policyChain.failWith(
        PolicyResult
                .failure(configuration.getErrorStatusCode(), errorContent));
```

I think it would be the best to apply EL to `errorContent` before passing it into PolicyResult.failure

**Comment by brasseld** [comment] 2020-03-27 07:36
Duplicate of https://github.com/gravitee-io/issues/issues/3188

**Closed by brasseld** 2020-03-27 07:36 UTC
