### ISSUE TITLE
[management] Health Check details can't be displayed 

### ISSUE THREAD

**Issue by apoddany** [gravitee-io/issues#7873] opened 2022-06-22 09:19 UTC
## :collision: Describe the bug
When enabling Health Check on an API and trying to display HC details (eye icon) on failure (i.e 502), no information can be found about the error : 

<img width="1403" alt="Capture d’écran 2022-06-22 à 11 17 02" src="https://user-images.githubusercontent.com/79909781/174992636-0c388f89-82bd-4456-9834-b01d88cf1096.png">

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Enable Health Check on an API
2. Have a failure in endpoint (502 on backend)
3. Check the HC details with the eye icon

## :movie_camera: Useful information
Screenshot, video, logs, other supporting material

## :computer: Desktop:

***Please complete the following information:***
 - Environment: 3.15.9

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

Link a story or other related things...

**Comment by mouligno** [comment] 2022-06-22 15:21
duplicate of https://github.com/gravitee-io/issues/issues/7841

**Closed by mouligno** 2022-06-22 15:21 UTC
Labels: type: bug, project: APIM, Reg, Support 2
