### ISSUE TITLE
[policy] [rate-limit] Inconsistent body for Rate Policy at V3.2

### ISSUE THREAD

**Issue by insertmike** [gravitee-io/issues#4344] opened 2020-09-25 21:09 UTC
#### Context
After I have upgraded from version 3.1 to 3.2 I have experienced an inconsistent behavior of management-api for rate-policy.

### Expected Behavior
The rate->limit and rate->periodTime numeric values to be either acceptable as STRING **or** INT. 

### Current Behavior
rate->limit is accepted only as STRING whereas rate->periodTime only as int. This makes the body inconsistent. Two numeric variables are accepted as different types. This behavior have been introduced with the new version of gravitee ( 3.2 ) and have not been present in ( 3.1 ) 
```
    {  "addHeaders":false,
       "async":false,
       "rate":{
          "limit":"100",
          "periodTime":1,
          "periodTimeUnit":"SECONDS"
       }
```

### Possible Solution
Make rate->limit and rate->periodTime consistent by making them one type.

### Steps to Reproduce (for bugs)

- Try adding a rate-policy by updating api via managament-api with rate->limit as int
- Try adding a rate-policy by updating api via managament-api with rate->periodTime as String
- Ensure a testing framework to test all policies before every release

### Your Environment

* Version used: 3.2

**Comment by bursauxa** [comment] 2020-09-29 15:34
Hello, this is because `limit` supports SpEL, so it can not be any JSON type other than string.

On the other hand, `periodTime` does not, so it is a numeric.

**Comment by brasseld** [comment] 2020-09-30 06:53
Duplicate of https://github.com/gravitee-io/issues/issues/4345

**Closed by brasseld** 2020-09-30 06:53 UTC
Labels: project: APIM, type: bug, type: duplicate
