### ISSUE TITLE
Dynamic properties API out of sync

### ISSUE THREAD

**Issue by vmargerin** [gravitee-io/issues#7269] opened 2022-03-10 08:36 UTC
## :collision: Describe the bug
Dynamic properties cron makes the API out of sync on each iteration. Properties value are refreshed in the UI (dynamic token section) but on the gateway side, it still the old values of the last deployment.

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. In the management UI, go to Design section of an API, then in the Dynamic properties section.
2. Create a CRON which call a remote service and maps the JSON response in properties.
3. Add the properties in a request header using Transform headers policy.
4. Deploy the API
5. On the next CRON iteration you will see the API out of sync.
6. Enable API logs
7. Make a request on the API and you will see that the header value is still the one of the latest deployment

## :rainbow: Expected behaviour
API should be synchronized on each CRON iteration and properties value refreshed on the Gateway side.

## :movie_camera: Useful information
![image](https://user-images.githubusercontent.com/78139283/157621052-1c6e9778-a59b-49d5-97fa-313ada4ee90d.png)

![image](https://user-images.githubusercontent.com/78139283/157620958-41e51dec-c79f-4730-8fb0-372219cb71d8.png)

Gravitee APIM 3.15.1
Helm Chart 3
OKD 4.7
Java 11

**Comment by brasseld** [comment] 2022-03-10 08:51
Duplicate of https://github.com/gravitee-io/issues/issues/5245#issuecomment-1052067076 ?

@mouligno can you please check with the team.

**Comment by vmargerin** [comment] 2022-03-10 13:10
@brasseld 
Contrary to this issue, I don't see any error in logs.

**Comment by vmargerin** [comment] 2022-03-15 14:30
As a workaround, I use Dictionnary feature with a dynamic type. The property value is refreshed as expected and the API doesn't appeared out of sync.

**Comment by LiliaEn** [comment] 2022-05-17 09:14
Tested on 3.15.x env
Browser: Chrome Version 99.0.4844.51 , macOS Big Sur v11.6
Working as expected

**Closed by LiliaEn** 2022-05-17 09:14 UTC
Labels: type: bug, project: APIM, p2, loop quantum, status: in test
