### ISSUE TITLE
[management] Cannot save API in some case with http headers

### ISSUE THREAD

**Issue by tapiiron** [gravitee-io/issues#4001] opened 2020-06-22 06:25 UTC
Gateway with bad healtcheck path causes API to start failing in few hours.

### Expected Behavior
When API-publisher publishes API and copy-pastes some url into basepath there should be some validation on path given or some mechanism to prevent API to start failing.

### Current Behavior
Currently if some publisher puts full url like http://www.google.com/check to healthcheck in API, the API works for a while and then starts failing fully as it has replaced its backend path with wrong heathcheck path. 

### Possible Solution
Prevent user to put bad input into heathcheck path or make the healtcheck not to break the whole api.

### Steps to Reproduce (for bugs)
1. create api
2. in backend settings put healthcheck on with wrong path like http://www.google.com/check (should be only /check)
3. start the api
4. notice that in 4 hours the backend path gets replaced as http://www.google.com/http://www.google.com/check 
5. nor the api or healthcheck works after this
6. stop and start to api fixes this and the api works for next 4 hours.

### Context
There are many users that can publish their apis. Errors in config are propable and in this case the error is not istantly there but starts after a while.

### Your Environment
* Version used: 1.03.11 and 3.0.3
* Browser Name and version: NA
* Operating System and version: RedHat8, OpenJDK11, PostgreSQL repository

**Comment by aelamrani** [comment] 2020-06-28 06:55
Hi @tapiiron 

I am not able to reproduce. May I ask you to share your API export?

**Comment by tapiiron** [comment] 2020-06-29 04:55
`{
  "name": "Broken API",
  "version": "1.1",
  "description": "Private Broken API",
  "visibility": "private",
  "paths": {
    "/api/trainingareagroups": [],
    "/api/realizations/:organizationcode/:year": [],
    "/api/indicatormeta/:externalid": [],
    "/api/indicatormeta": [],
    "/api/indicator/:externalid": [],
    "/api/indicator": []
  },
  "resources": [],
  "labels": [
    "nroken"
  ],
  "pages": [
    {
      "id": "f0227632-6ac4-4138-a276-326ac411381e",
      "name": "Aside",
      "type": "SYSTEM_FOLDER",
      "order": 0,
      "published": true,
      "lastModificationDate": 1592476729493,
      "contentType": "application/json",
      "configuration": {},
      "homepage": false,
      "metadata": {},
      "api": "6c50869f-72e1-4200-9086-9f72e1e200a4",
      "excluded_groups": []
    }
  ],
  "plans": [
    {
      "id": "fc04b5f9-9a73-4cc7-84b5-f99a737cc757",
      "name": "apikeyplan",
      "description": "Get an apikey here",
      "validation": "manual",
      "security": "api_key",
      "securityDefinition": "{\"propagateApiKey\":false}",
      "type": "api",
      "status": "published",
      "api": "6c50869f-72e1-4200-9086-9f72e1e200a4",
      "order": 1,
      "characteristics": [],
      "tags": [],
      "created_at": 1591355632527,
      "updated_at": 1591357207665,
      "published_at": 1591355647772,
      "paths": {
        "/": [
          {
            "methods": [
              "CONNECT",
              "DELETE",
              "GET",
              "HEAD",
              "OPTIONS",
              "PATCH",
              "POST",
              "PUT",
              "TRACE",
              "OTHER"
            ]
          }
        ]
      },
      "excluded_groups": [],
      "comment_required": false
    }
  ],
  "metadata": [
    {
      "key": "email-support",
      "name": "email-support",
      "format": "mail",
      "value": "some-email-som@where.com",
      "defaultValue": "some-email-som@where.com",
      "apiId": "6c50869f-72e1-4200-9086-9f72e1e200a4"
    }
  ],
  "path_mappings": [
    "/api/trainingareagroups",
    "/api/indicatormeta",
    "/api/indicator",
    "/api/indicator/:externalid",
    "/api/indicatormeta/:externalid",
    "/api/realizations/:organizationcode/:year"
  ],
  "proxy": {
    "virtual_hosts": [
      {
        "path": "/broken/api"
      }
    ],
    "strip_context_path": false,
    "preserve_host": false,
    "groups": [
      {
        "name": "default-group",
        "endpoints": [
          {
            "name": "default",
            "target": "https://someaddress/api",
            "weight": 1,
            "backup": false,
            "type": "HTTP",
            "healthcheck": {
              "enabled": true,
              "trigger": {
                "rate": 1,
                "unit": "HOURS"
              },
              "steps": [
                {
                  "name": "default-step",
                  "request": {
                    "path": "https://someaddress/api/api-doc",
                    "method": "GET",
                    "fromRoot": false
                  },
                  "response": {
                    "assertions": [
                      "#response.status == 200"
                    ]
                  }
                }
              ],
              "inherit": false
            },
            "http": {
              "connectTimeout": 5000,
              "idleTimeout": 60000,
              "keepAlive": true,
              "readTimeout": 10000,
              "pipelining": false,
              "maxConcurrentConnections": 100,
              "useCompression": true,
              "followRedirects": false
            },
            "proxy": {
              "enabled": false,
              "host": "null",
              "port": 0,
              "type": "HTTP"
            },
            "ssl": {
              "trustAll": false,
              "hostnameVerifier": false
            },
            "headers": {
              "apikey": "externalApikey"
            }
          }
        ],
        "load_balancing": {
          "type": "ROUND_ROBIN"
        },
        "http": {
          "connectTimeout": 5000,
          "idleTimeout": 60000,
          "keepAlive": true,
          "readTimeout": 10000,
          "pipelining": false,
          "maxConcurrentConnections": 100,
          "useCompression": true,
          "followRedirects": false
        }
      }
    ]
  },
  "response_templates": {}
}`

**Comment by tapiiron** [comment] 2020-06-29 04:58
Modified the export to anonymize the api. Part 
{
                  "name": "default-step",
                  "request": {
                    "path": "https://someaddress/api/api-doc",
                    "method": "GET",
                    "fromRoot": false
                  },
                  "response": {
                    "assertions": [
                      "#response.status == 200"
                    ]
                  }
                }

There should be only /api-doc in path-part. Otherwise the api starts to fail in 4 hours.

The API is not even editable at the moment with some json errors when updating from UI.

**Comment by aelamrani** [comment] 2020-06-29 05:35
Hi @tapiiron 

Can you also check the logs of the Gateway? Is there any error you can share?

>The API is not even editable at the moment with some json errors when updating from UI.

I just imported your API and no issue at all on my side, maybe you can paste here the browser's errors?

**Comment by tapiiron** [comment] 2020-06-29 05:43
Hey,
Nothing is shown in gateway logs. It just starts to fail after about 4 hours. 

About editing:
1) open endpoints -> endpoint edit -> healthcheck edit 
2) disable health check
3) press save
4) error: Cannot deserialize instance of `java.util.HashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.gravitee.rest.api.model.api.UpdateApiEntity["proxy"]). Backend api returns 400. No errors in management api logs.

**Comment by aelamrani** [comment] 2020-06-29 05:44
The API starts not working after 4 hours because you have configured a HC each 1 hour. So If there is 3 consecutive HC KO the gateway consider the endpoint not healthy and take it out from the pool of endpoints => so the behavior is normal here.

Also, the health check path must start with a `/` character and not a full URL.

Is it clearer?

I am now able to reproduce the error you mentioned here when trying to save, looking to fix this now.

**Comment by tapiiron** [comment] 2020-06-29 05:47
Yes. Can the "path" setting be validated fom user input? This was a misconfiguration by user who just copy-pasted the health check url into path-setting.

**Comment by aelamrani** [comment] 2020-06-29 05:50
Yes we should validate the input from UI and API.

**Comment by aelamrani** [comment] 2020-06-29 06:49
The problem on save will be fixed on the next 3.0.4.

For the validation of the path, actually it must not start with `/` as if the trailing slash is not provided, the gateway add it automatically. So you can provide something like: `api/_health`. That's why there is not validation here.

**Closed** 2020-06-30 14:01 UTC
Labels: project: APIM, status: in review, type: bug
