### ISSUE TITLE
Group role are lost after SCIM update

### ISSUE THREAD

**Issue by ppgravitee** [gravitee-io/issues#8591] opened 2022-10-21 15:20 UTC
When a group is updated usign SCIM, the roles assigned to the group are reset.

h1. How to reproduce

* Create a group on the UI
* assign a role to the group
* create a user and assign this user to the group
* Enable SCIM on the domain
* create a B2B application with the scim scope enabled by default
* get an access token for this B2B app
* call the SCIM groups endpoint to get the group description
* call the SCIM groups endpoint to update the memeber list (by removing the user)
* the role assign to the group should be reset

**Comment by leleueri** [comment] 2022-10-28 06:54
duplicate of #8584

**Closed** 2022-10-28 12:53 UTC
Labels: type: bug, project: AM
