### ISSUE TITLE
Duplication of accounts if authentication through Active Directory

### ISSUE THREAD

**Issue by grignix** [gravitee-io/issues#7849] opened 2022-06-17 15:16 UTC
## Describe the bug

Duplication of accounts if authentication through Active Directory if account move to another OU in Active Directory

## To Reproduce

Steps to reproduce the behaviour:

1.  Create a new account in Active Directory, for example, **adm**
2.  Give rights to **adm** account for any API in gravitee
3.  Login in gravitee under the account **adm**
4.  Сheck that we see API on which we gave the rights in step 2
5.  Logout from gravitee
6.  Move the **adm** account to another OU in Active Directory
7.  Login in gravitee under the account **adm**
8.  The rights are gone, we do not see any API
9.  See the reason, accounts are duplicated and the new account has no rights [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/26620272/174319453-8b493b74-88d8-48b0-83b8-e9cf444808e7.png)</span>](https://user-images.githubusercontent.com/26620272/174319453-8b493b74-88d8-48b0-83b8-e9cf444808e7.png) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/26620272/174319453-8b493b74-88d8-48b0-83b8-e9cf444808e7.png)</span>](https://user-images.githubusercontent.com/26620272/174319453-8b493b74-88d8-48b0-83b8-e9cf444808e7.png)

A unique identifier in Active Directory is better to use sAMAccountName Better yet, allows to specify a unique identifier and response timeout & other LDAP options in the config

It would be nice every 15 minutes(options in the config), for existing gravitee accounts, download changes from AD, upload a new photo from AD, or mark the account as disabled if it is disabled in AD

**Comment by mouligno** [comment] 2022-06-20 07:47
Hi @grignix 
Which version are you testing ?

**Comment by grignix** [comment] 2022-06-20 08:22
Checked in versions 3.5.x and 3.15.x but I suspect that the problem is in all versions

**Comment by djo54150** [comment] 2022-08-04 12:22
Hello, 

We have this issue in version 3.17.2.
I use the attribut **sAMAccountName** with this configuration:

`    - type: ldap
      context:
        username: "myUser"
        password: "myPWD"
        url: "MyLDAPUrl"
        base: "OU=IAM Users & Groups,DC=xx,DC=xx" 
      authentication:
        user:
          base: "OU=IAM Users"
          filter: "(&(objectClass=user)(sAMAccountName={0}))"
        group:
          base: "OU=Gravitee,OU=IAM Groups"
          filter: "(&(objectClass=group)(member={0}))"
          role:
            attribute: "cn"
            mapper: {
              Gravitee-admin: ADMIN,
              Gravitee-user: USER
            }
      lookup:
        allow-email-in-search-results: true
        user:
          base: "OU=IAM Users"
          filter: "(&(objectClass=user)(sAMAccountName={0}))"
`


At each connection the console creates a new user with the same data in DB: 

exemple: 
user 1 : 
`{
  "_id": "000c8272-4459-408b-8c82-724459108ba6",
  "organizationId": "DEFAULT",
  "firstname": "Jonathan",
  "lastname": "ALAGUERO",
  "source": "ldap",
  "sourceId": "cn=ALAGUERO Jonathan [IT],ou=IAM Users,ou=IAM Users & Groups,dc=xx,dc=xx",
  "status": "ACTIVE",
  "lastConnectionAt": {
    "$date": "2022-08-04T07:42:46.371Z"
  },
  "loginCount": 1,
  "firstConnectionAt": {
    "$date": "2022-08-04T07:42:46.371Z"
  },
  "createdAt": {
    "$date": "2022-08-04T07:42:46.209Z"
  },
  "updatedAt": {
    "$date": "2022-08-04T07:42:46.371Z"
  },
  "_class": "io.gravitee.repository.mongodb.management.internal.model.UserMongo"
}`


user2 : 
{
  "_id": "5b91415a-1b8c-42f9-9141-5a1b8cb2f935",
  "organizationId": "DEFAULT",
  "firstname": "Jonathan",
  "lastname": "ALAGUERO",
  "source": "ldap",
  "sourceId": "cn=ALAGUERO Jonathan [IT],ou=IAM Users,ou=IAM Users & Groups,dc=xx,dc=xx",
  "status": "ACTIVE",
  "lastConnectionAt": {
    "$date": "2022-08-04T07:44:03.858Z"
  },
  "loginCount": 1,
  "firstConnectionAt": {
    "$date": "2022-08-04T07:44:03.858Z"
  },
  "createdAt": {
    "$date": "2022-08-04T07:44:03.808Z"
  },
  "updatedAt": {
    "$date": "2022-08-04T07:44:03.858Z"
  },
  "_class": "io.gravitee.repository.mongodb.management.internal.model.UserMongo"
}


LDAP functionality is not usable. I think, it's not a P3 ;)

**Comment by phiz71** [comment] 2023-03-09 07:48
Duplicates #8673, which has been fixed in 3.15.19 and merged in upper branches.
https://docs.gravitee.io/apim/3.x/changelog-3.15.html#apim_3_15_19_2022_12_09

**Comment by grignix** [comment] 2023-03-09 14:40
@phiz71 Hi
issue [#7849](https://github.com/gravitee-io/issues/issues/7849) is not a duplicate of issue https://github.com/gravitee-io/issues/issues/8673
my problem is bad work gravitee-resource-auth-provider-ldap

A unique identifier in Active Directory is better to use sAMAccountName
Better yet, allow to specify a unique identifier and responsetimeout & other LDAP options in the config

It would be nice every 15 minutes(options in the config), for existing gravitee accounts, download changes from AD, upload a new photo from AD or mark the account as disabled if it is disabled in AD

**Comment by phiz71** [comment] 2023-03-10 08:34
Sorry @grignix, you're right!
Actually, #8673 fix the pb mentioned by @djo54150 in this current ticket (https://github.com/gravitee-io/issues/issues/7849#issuecomment-1205182556).

I reopen the bug, and we will have a look at it soon.

**Comment by ytvnr** [comment] 2023-03-30 07:19
Hello @grignix ,

Unfortunately, I was not able to reproduce the problem.
Would it be possible for you to export the `ldif` file (with users and groups configured) and also your `gravitee.yml` to check how you configured the LDAP security provider ?

Thank you in advance.

**Closed** 2023-11-12 18:25 UTC
Labels: type: bug, project: APIM, wontfix
