### ISSUE TITLE
Settings appear changeable, although only Read-Right was assigned

### ISSUE THREAD

**Issue by zveljanoski** [gravitee-io/issues#8746] opened 2022-12-19 10:54 UTC
## Describe the bug

Expecting not to be able to get to the api logging menu, but yet a user can

## To Reproduce

Steps to reproduce the behaviour: 

1.  Added the following permissions on organization level

<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/89140082/208408938-d1a75ee0-d051-4c5f-bf0c-64886decb12d.png)</span>

[!https://user-images.githubusercontent.com/89140082/208408938-d1a75ee0-d051-4c5f-bf0c-64886decb12d.png!](https://user-images.githubusercontent.com/89140082/208408938-d1a75ee0-d051-4c5f-bf0c-64886decb12d.png) 

2\. Expecting not to be able to access the api logging page, but yet able 

3\. If from ui: 

<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/89140082/208409375-29a9d715-aa1a-4a13-94e9-3891d5b456c8.png)</span>

[!https://user-images.githubusercontent.com/89140082/208409375-29a9d715-aa1a-4a13-94e9-3891d5b456c8.png!](https://user-images.githubusercontent.com/89140082/208409375-29a9d715-aa1a-4a13-94e9-3891d5b456c8.png)

cannot access the page, it throws an exception 

4\. When added this endpoint to the base url /environments/default/settings/groups/ 

<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/89140082/208409575-7d608d98-af8e-486b-bfd5-e36843ec38b5.png)</span>

[!https://user-images.githubusercontent.com/89140082/208409575-7d608d98-af8e-486b-bfd5-e36843ec38b5.png!](https://user-images.githubusercontent.com/89140082/208409575-7d608d98-af8e-486b-bfd5-e36843ec38b5.png)

5\. Been able to play (enable/disable) the buttons but not able to save/update with the new config 

6\. On another occurrence, reported that even from ui, able to access the settings->api logging page and do the same

**Comment by gaetanmaisse** [comment] 2023-07-12 09:40
The issue is fixed in the latest versions of APIM (at list 3.19+)

**Closed by gaetanmaisse** 2023-07-12 09:40 UTC
Labels: type: bug, project: APIM, p2, p3
