### ISSUE TITLE
Policy reset on gateway modification

### ISSUE THREAD

**Issue by SirBigoo** [gravitee-io/issues#716] opened 2017-08-02 13:34 UTC
Hi,

I faced a problem with gravitee : it resets policy when modifying an newly added gateway.
It seems it reset policy to state before added gateway even if it is modified afterwards.

### Expected Behavior
Policies should remain the same.

### Current Behavior
Policies are reseted

### Steps to Reproduce (for bugs)
1. Deploy an API with a gateway and a policy (in my case, it is a dynamic routing policy)
2. Add a new gateway
3. Deploy API
4. Modify policy (adding a new route or modifying existing)
5. Deploy API
6. Policy are ok : there are modified
7. Modify gateway (proxy or name)
8. Deploy API
9. Look at policies : there are reseted in the state before adding new gateway

### Context
I was adding a new gateway country, so I have to modify my exiting API and polices. My gateway was not properly configured (proxy not set) so I had to modify configuration.

### Your Environment
* Version used: 1.8.0
* Browser Name and version: Google chrome 58.0.3029.96 (64-bit)
* Operating System and version: Linux Mint 17.3 Cinnamon 64-bit

**Comment by brasseld** [comment] 2017-08-03 07:21
Duplicate of: #662

**Comment by aelamrani** [comment] 2017-09-15 13:15
Duplicate of #618

**Closed by aelamrani** 2017-09-15 13:15 UTC
