### ISSUE TITLE
Provide the risk assessment data to the risk assessment service 

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7656] opened 2022-05-13 09:08 UTC
## :rainbow: Feature

**As a** '...'

**I want to** '...'

**So that** '...'

## :sunrise_over_mountains: Additional information

Detailed behaviour, rules or additional interesting stuffs...

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:

**Comment by tcompiegne** [comment] 2022-05-30 11:39
Duplicate of #7657

**Closed by tcompiegne** 2022-05-30 11:39 UTC
Labels: type: feature, project: AM
