### ISSUE TITLE
KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory.

### ISSUE THREAD

**Issue by riosje** [gravitee-io/issues#3844] opened 2020-05-24 00:31 UTC
API Management 1.30.10 cant load Keystore
### Expected Behavior
The API management should be able to load keystore with multiple certs.

### Current Behavior
The API management is not able to load keysotre with multiple  due to jetty issue.

### Possible Solution
Updating [jetty.util.ssl.SslContextFactory](https://www.eclipse.org/jetty/javadoc/9.4.19.v20190610/org/eclipse/jetty/util/ssl/SslContextFactory.html#%3Cinit%3E()) because it is deprecated 
We should use: 
org.eclipse.jetty.util.ssl.SslContextFactory$Server
org.eclipse.jetty.util.ssl.SslContextFactory$Client 

jetty.util.ssl.SslContextFactory is deprecated now

### Steps to Reproduce (for bugs)
RUN API management 1.30.10
LOAD keystore with multiple CERTS.

**Comment by riosje** [comment] 2020-05-24 00:42
This error is criticar because is common to hace the certs of the CA and SUB-CA in the same keystore.

**Comment by md-mg** [comment] 2020-05-25 11:26
Duplicate of #3820?

**Comment by brasseld** [comment] 2020-05-25 14:28
yes it is a duplicate @md-mg 

This will be fixed in 1.30.11

**Closed** 2022-04-30 23:59 UTC
