### ISSUE TITLE
 [policy] [rate-limit] E11000 duplicate key error collection: gravitee.ratelimit

### ISSUE THREAD

**Issue by David-V2** [gravitee-io/issues#1002] opened 2018-01-17 09:29 UTC
The first four requests of an API load test always give me error (500)

### Your Environment
* Version used: 1.10.5
* 2 Public gateway routing request to 2 private gateway

### Current Behavior
With a very long ramp up period, I do not have any error. With a short one, I have the first four request in error.
Here is a sample gateway stack-trace

```
io.gravitee.gateway.policy.PolicyChainException: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:46)
    at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:66)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
    at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.lambda$execute$0(RequestPolicyChainProcessor.java:57)
    at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:76)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.policy.apikey.ApiKeyPolicy.onRequest(ApiKeyPolicy.java:94)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:44)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44)
    at io.gravitee.gateway.policy.impl.PolicyChain.doNext(PolicyChain.java:66)
    at io.gravitee.gateway.policy.impl.StreamablePolicyChain.doNext(StreamablePolicyChain.java:51)
    at io.gravitee.gateway.policy.impl.RequestPolicyChainProcessor.execute(RequestPolicyChainProcessor.java:63)
    at io.gravitee.gateway.handlers.api.ApiReactorHandler.handleClientRequest(ApiReactorHandler.java:178)
    at io.gravitee.gateway.handlers.api.ApiReactorHandler.doHandle(ApiReactorHandler.java:122)
    at io.gravitee.gateway.reactor.handler.AbstractReactorHandler.handle(AbstractReactorHandler.java:87)
    at io.gravitee.gateway.reactor.impl.DefaultReactor.lambda$route$0(DefaultReactor.java:87)
    at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:58)
    at io.gravitee.gateway.reactor.handler.transaction.TransactionHandler.handle(TransactionHandler.java:29)
    at io.gravitee.gateway.reactor.impl.DefaultReactor.route(DefaultReactor.java:98)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handleRequest(VertxReactorHandler.java:39)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:35)
    at io.gravitee.gateway.standalone.vertx.VertxReactorHandler.handle(VertxReactorHandler.java:25)
    at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:285)
    at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:429)
    at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:763)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:757)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:676)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573)
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
    at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1064)
    at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:1035)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.gravitee.gateway.policy.PolicyException: java.lang.reflect.InvocationTargetException
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:91)
    at io.gravitee.gateway.policy.impl.PolicyImpl.onRequest(PolicyImpl.java:44)
    at io.gravitee.gateway.policy.impl.RequestPolicyChain.execute(RequestPolicyChain.java:44)
    ... 62 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.gravitee.gateway.policy.impl.PolicyImpl.invoke(PolicyImpl.java:89)
    ... 64 more
Caused by: com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: gravitee.ratelimit index: _id_ dup key: { : "360a3560-f38f-4adc-8a35-60f38fbadc4a:rl:" }'
    at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:243)
    at com.mongodb.operation.BaseWriteOperation.access$300(BaseWriteOperation.java:60)
    at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:144)
    at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133)
    at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
    at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
    at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133)
    at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60)
    at com.mongodb.Mongo.execute(Mongo.java:845)
    at com.mongodb.Mongo$2.execute(Mongo.java:828)
    at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342)
    at com.mongodb.DBCollection.replaceOrInsert(DBCollection.java:420)
    at com.mongodb.DBCollection.save(DBCollection.java:409)
    at com.mongodb.DBCollection.save(DBCollection.java:382)
    at io.gravitee.repository.mongodb.ratelimit.MongoRateLimitRepository.save(MongoRateLimitRepository.java:104)
    at io.gravitee.gateway.service.ratelimit.DefaultRateLimitService.save(DefaultRateLimitService.java:38)
    at io.gravitee.policy.ratelimit.RateLimitPolicy.onRequest(RateLimitPolicy.java:128)
    ... 69 more
```

**Comment by SirBigoo** [comment] 2018-01-30 09:33
Hello,

Any news about this bug ?

Thanks.

**Comment by brasseld** [comment] 2018-01-30 13:19
Hi @SirBigoo,

Not at all!
This issue is not critical currently so you may have to wait for next versions of Gravitee.io.

Regards,

**Comment by NicolasGeraud** [comment] 2018-03-02 16:06
hi @SirBigoo 
are you a coworker of @David-V2 ?
If no, can you tell me if this error occurs only on a fresh mongo database (without any collections) or if it occurs on a database where the collection `ratelimit` already exists ?

**Comment by SirBigoo** [comment] 2018-03-20 08:20
Hello @NicolasGeraud 
When we had this issue, it is not from a fresh mongo database.

**Comment by NicolasGeraud** [comment] 2018-03-20 08:25
Can you describe a little more how to reproduce it ?

Because on my side, the only way to reproduce the DuplicateKey exception is to launch 2 gateway instance with an empty mongo and launch a load test.

**Comment by brasseld** [comment] 2020-01-07 13:09
Closed by https://github.com/gravitee-io/issues/issues/2570

**Closed by brasseld** 2020-01-07 13:09 UTC
Labels: type: bug
