### ISSUE TITLE
[management] Allow an API Publisher to push API Metrics to a specific target

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5349] opened 2021-04-02 07:48 UTC
An API Publisher should be able to configure in an API a destination target so the gateway can push API metrics to that target.
The destination target could be a TCP socket or an HTTP endpoint.

**Comment by patelami** [comment] 2021-04-29 06:56
@brasseld : Is it possible to test this ticket nightly?

**Comment by brasseld** [comment] 2021-05-05 06:37
@patelami you can create a second API you are calling by using the policy.
For this API, enable logging, this way, you will see the data from the payload.

**Comment by patelami** [comment] 2021-05-06 12:30
Env: Local dev (master)

Given I have an API named A with a free plan ( context path /eco)
A nd I have enable logs for the API A
And I have created an API named B with metrics reporter policy  (context path /metrics)
And in the metrics reporter policy: I have specified the URL for API A(example: http://localhost:8082/eco)
And I call API B with  curl "http://localhost:8082/metrics"
And I check logs for API A
Then I should see header/body of API B in the logs

**Comment by patelami** [comment] 2021-05-06 14:01
On nightly env. we are unable to see the request body. The issue is related to this: https://github.com/gravitee-io/issues/issues/5364. hence not closing this ticket.

**Comment by aelamrani** [comment] 2021-05-06 14:15
@patelami just to be sure to understand, do you say that the tests are failing? Or you are not able to validate this issue (even by inspecting the network)?

**Comment by patelami** [comment] 2021-05-07 08:25
payload missing in UI Issue #5364 is not related to this ticket, hence closing this ticket. We can see the request body pay load in the network request.

**Closed** 2021-05-07 08:25 UTC
Labels: project: APIM, type: feature
