### ISSUE TITLE
Closing a plan seems quite long

### ISSUE THREAD

**Issue by jhaeyaert** [gravitee-io/issues#7893] opened 2022-06-24 05:41 UTC
## :collision: Describe the bug
On apim-master (latest 3.19.0-SNAPSHOT), try to close a plan takes more time than before

On the following screenshot you can see that the call to retrieve the subscriptions associated to the plan takes more than 4s (I experiences the same on my local environment).

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/5955401/175469421-481b73c6-52fb-427b-8f72-15363dcf36df.png">

## :sunrise_over_mountains: To Reproduce
Steps to reproduce the behaviour:
1. Go to an api having plan
2. Click on close plan
3. See how much time it takes

## :rainbow: Expected behaviour
N/A

## Current behaviour
N/A

## :movie_camera: Useful information
N/A

## :computer: Desktop:

***Please complete the following information:***
 - Environment: latest master branch (3.19.0-SNAPSHOT)
 - OS:  macos
 - Browser chrome

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :link: Dependencies

N/A

**Comment by gaetanmaisse** [comment] 2022-09-20 07:25
Closing as it looks the issue isn't here anymore, see on 3.19.x env ⬇️ 
<img width="2041" alt="image" src="https://user-images.githubusercontent.com/4112568/191193737-605709d4-f7c1-4265-b223-3f015b53bcb2.png">

**Closed by gaetanmaisse** 2022-09-20 07:25 UTC
Labels: type: bug, project: APIM, need-investigation
