### ISSUE TITLE
[gateway] Manage redirect 3xx

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/issues#541] opened 2017-04-19 12:31 UTC
Hello,

### Context
A team has move one of their endpoint from url A to B. (host change)
On the previous url (A), they now reply with a 302 redirect to B.

But currently, the gateway is not able to manage 302, so this 302 is returned to the client.

### Expected Behavior
That would be nice that the gateway is able to manage 302 (so call the B and then return the response) instead of returning the 302 to the client.

Regards,
Alexandre.

**Comment by smile59** [comment] 2017-04-26 08:58
API must not redirect on other API even if they were been moved and/or they are the same. You must use the API Manager to manage that things of updates / changes.

The reason is simple : you're not sure the host A will stay online to redirect to B. And you'll pay 2 servers for X times.

**Comment by lusoalex** [comment] 2017-04-27 13:09
Hi,

I agree, that was my first idea, but that means they need to sync all the tasks in this order :

1. Deploy services on Host B
2. Do the changes on the API Management
3. Stop services on Host A.

By the way, it's not something that should happen often, especially if we are able to manage it through a strong CI.

But that may happen anyway... (For me this is not an important feature)
Alexandre.

**Comment by brasseld** [comment] 2017-09-13 15:36
Duplicate of https://github.com/gravitee-io/issues/issues/778

**Closed by brasseld** 2017-09-13 15:36 UTC
Labels: type: question
