### ISSUE TITLE
Whitelist path pattern should use endpoints

### ISSUE THREAD

**Issue by AudricCh** [gravitee-io/issues#2769] opened 2019-10-23 10:28 UTC
Hi,

On the API manager, when we put on a plan a whitelist restriction on a path, the path must contains the whole path.

### Expected Behavior

Swagger example :
![image](https://user-images.githubusercontent.com/25503027/67383758-21a3f600-f590-11e9-8084-3fced843d325.png)

On the path pattern, we should only specify the endpoint name. Example :
![image](https://user-images.githubusercontent.com/25503027/67383639-d25dc580-f58f-11e9-8d51-dd0b7878728c.png)

### Current Behavior

What we have to do is write the complete path from the version like that :
![image](https://user-images.githubusercontent.com/25503027/67383849-4a2bf000-f590-11e9-9ee4-f82917a26a5f.png)

### Context
The goal is to simplify and help the developer to add only the enPoint he needs, and not the complete URL.

Thanks !

**Comment by aelamrani** [comment] 2019-10-23 10:45
Hi @AudricCh 
You should be able to describe your rules with ant pattern.

For your example, this should work as expected: `/**/Secret/*`

**Comment by AudricCh** [comment] 2019-10-23 12:22
Perfect ! Thanks.
There is maybe a little lack of information in the documentation IMHO.

**Comment by aelamrani** [comment] 2019-10-23 12:24
Allright 👍

**Comment by brasseld** [comment] 2019-10-25 07:59
Duplicate of https://github.com/gravitee-io/issues/issues/1271

**Closed by brasseld** 2019-10-25 07:59 UTC
Labels: project: APIM, type:need_documentation
